### ISSUE TITLE
sending message feature

### ISSUE THREAD

**Issue by knsrky** [bstoilov/py3-pinterest#10]
hello, can we send messages to Pinterest users? how can we do that?

**Comment by bstoilov** [comment]
Can you say that in english

**Comment by knsrky** [comment]
hahaha I'm sorry I wrote it in the wrong language :)

**Comment by bstoilov** [comment]
Haha, no problem. Currently there is no such feature. I will mark this as feature request.

**Comment by bstoilov** [comment]
Hello, here is a PR that adds support for direct messages.
I tested most cases but it would be nice if more testing is done.

https://github.com/bstoilov/py3-pinterest/pull/17

I will merge it in two days if there are no concerns.

**Comment by knsrky** [comment]
it works! thank you so much @bstoilov :)

**Comment by bstoilov** [comment]
Happy spamming :smile:
