### ISSUE TITLE
Unable to import 'py3pin.Pinterest'pylint(import-error)

### ISSUE THREAD

**Issue by 3BDN16** [bstoilov/py3-pinterest#100]
Hi I have problem with importing your py3-pinterest module. I've used pip install py3-pinterest command and it installed successfully, but i can't import it 😢 

I tried changing interpreter and reinstalling it. Still doesn't work.

**Comment by bstoilov** [comment]
Strange, can you post your code?

**Comment by 3BDN16** [comment]
The code is very simple because i wanted to test it, if I can log in to my pinterest

`from py3pin.Pinterest import Pinterest

pinterest = Pinterest(email='{email}',
                      password='{password}',
                      username='{username}',
                      cred_root='cred_root')
pinterest.login()`

I'm new to programming and I'm not sure if I did everything correct

**Comment by bstoilov** [comment]
Are you sure the module is installed?

What is the output from

`pip install py3-pinterest`

you can also try with pip3 if pip one doesn't work. This happens to me when I am on linux.

Also can you post the exact error you are getting on import

**Comment by 3BDN16** [comment]
![image](https://user-images.githubusercontent.com/73472103/101287933-a7661d80-37f3-11eb-935a-fe629877ffff.png)

It seems like it's all properly installed

**Comment by bstoilov** [comment]
And how are you running your python script? I suspect PowerShell is the problem. I have never tried running it inside powershell, in theory it shouldn't be a problem but.. you never know with these windows tools

**Comment by bstoilov** [comment]
@3BDN16 still having problems?
