### ISSUE TITLE
Trying to get pin ids of a board, but I get nothing

### ISSUE THREAD

**Issue by jjb99** [bstoilov/py3-pinterest#101]
hi, thanks for the code,
I am trying to get Pin ids of a board (id), use the following code which I got it from your answer on an issue [Here](https://github.com/bstoilov/py3-pinterest/issues/78), but I get empty list, 

what do I wrong?
perhaps some people who use this feature help me out here.
Thanks

`pinterest.boards_all(username='AccountName1')
all_boards = pinterest.boards_all(username='AccountName1')

def get_board_pins_batched(board_id='536561811794494658'):
    board_feed = []
    feed_batch = pinterest.board_feed(board_id=board_id)
    while len(feed_batch) > 0:
        board_feed += feed_batch
        feed_batch = pinterest.board_feed(board_id=board_id)
    #print(board_feed)
    return board_feed
user_pins = []
for board in all_boards:
        user_pins += get_board_pins_batched(board['id'])
print(user_pins)`

output:
[]

**Comment by bstoilov** [comment]
Work fine by my
Try this code

```
boards = pinterest.boards_all()

for b in boards:
    print("Board id " + b['id'] + " board name " + b['name'])
```

Tell me if you have problems with it, it should give all boards of the currently logged in account if no username is specified. To specify username

`boards = pinterest.boards_all(username='user')`

**Comment by jjb99** [comment]
thanks,  it works partially.
 if I don't put a username, yes it will prints out my Board name and Ids.,
but if I fill a username, it will print my Board and IDs again.
I tried this:
`boards = pinterest.boards_all(username='samanthahammack')

boards = pinterest.boards_all()

for b in boards:

    print("Board id " + b['id'] + " board name " + b['name'])`

**Comment by bstoilov** [comment]
`boards = pinterest.boards_all(username='samanthahammack')`
boards conatains all the boards of user samanthahammack

`boards = pinterest.boards_all()`
boards get overwriten to conatain all of your boards

```
boards = pinterest.boards_all(username='samanthahammack')

for b in boards:
    print("Board id " + b['id'] + " board name " + b['name'])
```

This code does what you want
