### ISSUE TITLE
what is the solution for login() session when you already logged in

### ISSUE THREAD

**Issue by jjb99** [bstoilov/py3-pinterest#104]
Edited:
I am using : __version__ = '1.1.3'
Hello, I use some part of your code on cloud and now testing it for schedule once per day,
I have another session using same Pinterest account doing some tasks on IFTTT which requires also login to same Pinterest account.

now I want to know if it is OK to logout after the task is done, and when another day it is time to run it again, do the login.
so This way: 

`pinterest = Pinterest(email='xxxx',

			password='xxxx',

			username='xxxx',

			cred_root='cred_root')

pinterest.login()

def repin(pin_id='somePinID', board_id='MyBoardID', section_id=None):

    return pinterest.repin(board_id=board_id, pin_id=pin_id, section_id=section_id)

repin()

pinterest.logout()`

I have problem when running the code on my machine, so it tries to login, and at the same time I have open Pinterest on browser using VPN which is on another IP address than the Visual Studio Code .

so there will be a problem, and Pinterest log me out and wants me to change the password.

1- I am not sure if this `pinterest.login()` is requiered or not.
2- Is is OK to log out each time?
if there is another solution I am grateful to know about it.

thank you.

**Comment by bstoilov** [comment]
No need to login every time. Logout is just added for convenience, no need to logout either.

The session will be valid for some time (they keep changing the validity time). So you just need to call login once in a while if you start getting unauthorized errors
