### ISSUE TITLE
Failed to create Pin

### ISSUE THREAD

**Issue by Kumail420** [bstoilov/py3-pinterest#110]
PIN_RESOURCE_CREATE = 'https://www.pinterest.com/resource/PinResource/create/'
this url is not working, gives error 
HTTPError: 404 Client Error: Not Found for url: https://www.pinterest.com/resource/PinResource/create/

**Comment by bstoilov** [comment]
Can you share the code you are using. This can happen if there is no such board id

**Comment by Velos31** [comment]
I have the same issue. My code is just copied from the example file as I was simply testing everything:
`from py3pin.Pinterest import Pinterest

pinterest = Pinterest(email = email, password = password, username = username)
pinterest.login()

board_id = ''
section_id = None
image_url = 'https://i.pinimg.com/170x/32/78/bd/3278bd27073e1ec9c8a708409279768b.jpg'
description = 'this is a pin'
title = 'i did this'
link = 'https://www.google.com/'

pinterest.pin(board_id = board_id, section_id = section_id, image_url = image_url, description = description, title = title, link = link)`
The error message is the same:
HTTPError: 404 Client Error: Not Found for url: https://www.pinterest.com/resource/PinResource/create/
