### ISSUE TITLE
No credentials stored [Errno 2] No such file or directory: 'data/my@mail'

### ISSUE THREAD

**Issue by dejurin** [bstoilov/py3-pinterest#113]
```
from py3pin.Pinterest import Pinterest

pinterest = Pinterest(email='my@mail',
                      password='pass',
                      username='username')


```

**Comment by imgVOID** [comment]
Me too

**Comment by bstoilov** [comment]
you are not passing the cred_root parameter

`Pinterest(email='your email goes here', password='password goes here', username='look in pinterest url', cred_root='cred root dir')`

try providing it and see if that helps

**Comment by dejurin** [comment]
> you are not passing the cred_root parameter
> 
> `Pinterest(email='your email goes here', password='password goes here', username='look in pinterest url', cred_root='cred root dir')`
> 
> try providing it and see if that helps

I was try

```
from py3pin.Pinterest import Pinterest

pinterest = Pinterest(email='mail@gmail.com',
                      password='pass',
                      username='https://www.pinterest.com/myURL/')
```
```
No credentials stored [Errno 2] No such file or directory: 'data/mail@gmail.com'
```

**Comment by bstoilov** [comment]
Did you call login? 'data' is the default location of the credentials, there is a logic to make sure the directory exists etc.

**Comment by imgVOID** [comment]
Previously, the program itself created a directory, if that does not exist, now it gives an error. In my case directory have been created, but the program show the error too. 
I think it can be an error with the Windows' and UNIX difference in the path slashes, but I'm not shure about it.

**Comment by dejurin** [comment]
> Did you call login? 'data' is the default location of the credentials, there is a logic to make sure the directory exists etc.

sure, 'data' created but nothing else.

**OS**: OSX 11.0.1
**VERSION**: Python 3.9.1

**Comment by bstoilov** [comment]
Works on my machine, I have to test it on a different one and windows apparently.

Shouldn't be a os specific path problem since I am using this

`os.path.join(self.root, self.username)`

**Comment by imgVOID** [comment]
> 
> 
> Works on my machine, I have to test it on a different one and windows apparently.
> 
> Shouldn't be a os specific path problem since I am using this
> 
> `os.path.join(self.root, self.username)`

U're right, so we need to do some fixes with the os pathes
my Windows say that there isnt any "\\data" (double slash) folder.

**Comment by dejurin** [comment]
I was add fullpath, but not work.
```python
    def _get_cred_file_path(self):
        return os.path.join('/Users/admin/pin' + self.root, self.username)
```
```
No credentials stored [Errno 2] No such file or directory: 
```
Script not create file.

**Comment by imgVOID** [comment]
> 
> 
> I was add fullpath, but not work.
> 
> ```python
>     def _get_cred_file_path(self):
>         return os.path.join('/Users/admin/pin' + self.root, self.username)
> ```
> 
> ```
> No credentials stored [Errno 2] No such file or directory: 
> ```
> 
> Script not create file.

Check your Windows admin permissions and write access.
And go to fix [https://github.com/bstoilov/py3-pinterest/blob/master/py3pin/Registry.py](this file)

**Comment by dejurin** [comment]
> > I was add fullpath, but not work.
> > ```python
> >     def _get_cred_file_path(self):
> >         return os.path.join('/Users/admin/pin' + self.root, self.username)
> > ```
> > 
> > 
> > ```
> > No credentials stored [Errno 2] No such file or directory: 
> > ```
> > 
> > 
> > Script not create file.
> 
> Check your Windows admin permissions and write access.
> And go to fix [this file](https://github.com/bstoilov/py3-pinterest/blob/master/py3pin/Registry.py)

I'm use MAC, I was try run with root permissions, but doest work.
PS: you run this script successful on windows?

**Comment by imgVOID** [comment]
> PS: you run this script successful on windows?

After the captcha update no, but before - yes many times

**Comment by imgVOID** [comment]
You know that only the one way to release your problem is to fix [this file](https://github.com/bstoilov/py3-pinterest/blob/master/py3pin/Registry.py)
`try:
            with open(self._get_cred_file_path()) as f:
                content = f.read()
                self.cookies = json.loads(content)
        except Exception as e:
            print("No credentials stored", e)
`

**Comment by bstoilov** [comment]
I was not able to reproduce the issue in any way on my linux machine. Probably it is an os specific thing. I will try on mac and windows and let you know

**Comment by bstoilov** [comment]
Works on all win and mac

**Comment by animemoeus** [comment]
same problem, Ubuntu 20.04

`No credentials stored [Errno 2] No such file or directory: 'data/my@email.com'`

**Comment by bstoilov** [comment]
@animemoeus Is the login sucessful?

**Comment by animemoeus** [comment]
> @animemoeus Is the login sucessful?

Yes, but I need to log in every time

```
No credentials stored [Errno 2] No such file or directory: 'data/my.@email.com'
 
[WDM] - Current google-chrome version is 87.0.4280
[WDM] - Get LATEST driver version for 87.0.4280
[WDM] - Driver [/home/user/.wdm/drivers/chromedriver/linux64/87.0.4280.88/chromedriver] found in cache
Failed to login Message: 

Successfully logged in with account my@email.com
```

**Comment by imgVOID** [comment]
> 
> 
> > @animemoeus Is the login sucessful?
> 
> Yes, but I need to log in every time
> 
> ```
> No credentials stored [Errno 2] No such file or directory: 'data/my.@email.com'
>  
> [WDM] - Current google-chrome version is 87.0.4280
> [WDM] - Get LATEST driver version for 87.0.4280
> [WDM] - Driver [/home/user/.wdm/drivers/chromedriver/linux64/87.0.4280.88/chromedriver] found in cache
> Failed to login Message: 
> 
> Successfully logged in with account my@email.com
> ```

I had this problem yesterday. In my case, it was because Windows Defender was clearing my ADMIN ROOT PRIVILEGES !!!

**Comment by imgVOID** [comment]
So it's 99% that you have troubles with the OS write privileges or the antivirus settings.
