### ISSUE TITLE
KeyError: 'images'

### ISSUE THREAD

**Issue by vriadlee** [bstoilov/py3-pinterest#114]
When I run **download_board_images.py**, it downloads the images from my first board, then exits with this error:

```
Traceback (most recent call last):
  File "download_board_images.py", line 41, in <module>
    url = pin['images']['orig']['url']
KeyError: 'images'
```
Here's the output in whole:

```
No credentials stored [Errno 2] No such file or directory: 'cred_root/vriad_lee@chushka.com'
Downloading https://i.pinimg.com/originals/13/1e/90/131e905a1d4989f75139cbe8352c5d78.jpg
Downloading https://i.pinimg.com/originals/e9/51/34/e9513427006bfe5e7a35775c1b463541.jpg
Traceback (most recent call last):
  File "download_board_images.py", line 41, in <module>
    url = pin['images']['orig']['url']
KeyError: 'images'
```

**Comment by vriadlee** [comment]
Now that I've looked into this, it turns out not every object in the "pin" object has an "image" field. So changing the script as follows solved the issue:

```
    for pin in board_pins:
        **if 'images' in pin:**
            url = pin['images']['orig']['url']
```

To skip previously downloaded files, I added this:

```
    def download_image(url, path):
        **if os.path.isfile(path):
            print ("File exists")
        else:**
            print("Downloading " + path)
```  

To go over all the boards of the user and to create a separate directory for each board:

```
for board in boards:
    target_board = board
    print(target_board['name'])
    if not os.path.exists(download_dir + target_board['name']):
        os.makedirs(download_dir + target_board['name']) 
```
and 

```
    for pin in board_pins:
        if 'images' in pin:
            url = pin['images']['orig']['url']
            download_image(**url, download_dir + target_board['name'] + '/' + url.rsplit('/', 1)[-1]**)
```

To avoid **Connection reset by peer** error:

```
    def download_image(url, path):
        if os.path.isfile(path):
            print ("File exists")
        else:
            print("Downloading " + path)
            **nb_tries = 10
            while True:
                nb_tries -= 1
                try:
                    # Request url
                    r = requests.get(url=url, stream=True)
                    break
                except ConnectionError as err:
                    if nb_tries == 0:
                        raise err
                    else:
                        time.sleep(1)  
            if r.status_code == 200:**
                with open(path, 'wb') as f:
                    for chunk in r.iter_content(1024):
                        f.write(chunk)
```

**Comment by vriadlee** [comment]
Now that I've looked into this, it turns out not every object in the "pin" object has an "image" field. So changing the script as follows solved the issue:

    for pin in board_pins:
        **if 'images' in pin:**
            url = pin['images']['orig']['url']

To skip previously downloaded files, I added this:

    def download_image(url, path):
        **if os.path.isfile(path):
            print ("File exists")
        else:**
            print("Downloading " + path)

To go over all the boards of the user and to create a separate directory for each board:

for board in boards:
    target_board = board
    print(target_board['name'])
    if not os.path.exists(download_dir + target_board['name']):
        os.makedirs(download_dir + target_board['name']) 

and

    for pin in board_pins:
        if 'images' in pin:
            url = pin['images']['orig']['url']
            download_image(**url, download_dir + target_board['name'] + '/' + url.rsplit('/', 1)[-1]**)

To avoid Connection reset by peer error:

    def download_image(url, path):
        if os.path.isfile(path):
            print ("File exists")
        else:
            print("Downloading " + path)
            **nb_tries = 10
            while True:
                nb_tries -= 1
                try:
                    # Request url
                    r = requests.get(url=url, stream=True)
                    break
                except ConnectionError as err:
                    if nb_tries == 0:
                        raise err
                    else:
                        time.sleep(1)  
            if r.status_code == 200:**
                with open(path, 'wb') as f:
                    for chunk in r.iter_content(1024):
                        f.write(chunk)

**Comment by bstoilov** [comment]
Alright this is new. I will test your code once I have time.

Thanks :)

**Comment by bstoilov** [comment]
https://github.com/bstoilov/py3-pinterest/pull/121/files
I have included your changes here and made every board images to be downloaded into a dedicated sub dir for the board to be more organized.

**Comment by bstoilov** [comment]
Just realized you alredy did it in a PR. I merged yours and discarder my changes. THanks :)
