### ISSUE TITLE
Need clarification on login with cookies

### ISSUE THREAD

**Issue by carolhng** [bstoilov/py3-pinterest#115]
Hi, I am new user for py3pin. I need clarification on pinterest login using latest updated version.

When I login for the first time with pinterest.login(), the script stored cookies in my local disk (yes I confirm that).

Then for the next login, I still seeing script try to enter email and password. Is that mean script doing relogin without cookies?

Based on the example provided, if I want to let the script using cookies to login, is that mean I have to comment out pinterest.login() and script will autologin?

Thank you.

# login will obtain and store cookies for further use, they last around 15 days.
# NOTE: Since login will store the cookies in local file you don't need to call it more then 3-4 times a month.
# pinterest.login()

**Comment by bstoilov** [comment]
Every time you call login, the script will try to obtain the cookies. It can't know if the cookies are valid until a request fails with 'unauthorized' this is why you have to manually handle this. Like mentioned call login for the accounts every 10-15 days.

**Comment by carolhng** [comment]
thank you!
