### ISSUE TITLE
Unable to Install on Ubuntu 18.04 and 20.04

### ISSUE THREAD

**Issue by mazharoddin** [bstoilov/py3-pinterest#119]
Hi,
I am trying to install py3-pinterest on the latest versions of Ubuntu. On both 18.04 and 20.4 installation is failing with the below error. 

pip3 install py3-pinterest
Collecting py3-pinterest
  Using cached py3-pinterest-1.2.1.tar.gz (15 kB)
Collecting PyQt5
  Using cached PyQt5-5.15.2-5.15.2-cp35.cp36.cp37.cp38.cp39-abi3-manylinux2014_x86_64.whl (68.3 MB)
Collecting beautifulsoup4
  Using cached beautifulsoup4-4.9.3-py3-none-any.whl (115 kB)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from py3-pinterest) (2.22.0)
Collecting requests-toolbelt
  Using cached requests_toolbelt-0.9.1-py2.py3-none-any.whl (54 kB)
Collecting selenium
  Using cached selenium-3.141.0-py2.py3-none-any.whl (904 kB)
Collecting webdriver-manager
  Using cached webdriver_manager-3.2.2-py2.py3-none-any.whl (16 kB)
Collecting soupsieve>1.2; python_version >= "3.0"
  Using cached soupsieve-2.1-py3-none-any.whl (32 kB)
Requirement already satisfied: urllib3 in /usr/lib/python3/dist-packages (from selenium->py3-pinterest) (1.25.8)
Collecting configparser
  Using cached configparser-5.0.1-py3-none-any.whl (22 kB)
Collecting crayons
  Using cached crayons-0.4.0-py2.py3-none-any.whl (4.6 kB)
Requirement already satisfied: colorama in /usr/lib/python3/dist-packages (from crayons->webdriver-manager->py3-pinterest) (0.4.3)
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    PyQt5 from https://files.pythonhosted.org/packages/91/cf/cc705497cdae04c3c0bc34f94b91e31b6585bb65eb561f18473c998caae1/PyQt5-5.15.2-5.15.2-cp35.cp36.cp37.cp38.cp39-abi3-manylinux2014_x86_64.whl#sha256=29889845688a54d62820585ad5b2e0200a36b304ff3d7a555e95599f110ba4ce (from py3-pinterest):
        Expected sha256 29889845688a54d62820585ad5b2e0200a36b304ff3d7a555e95599f110ba4ce
             Got        7ce93dafbcf6f83011f3d0c18ed59f65d9281468a20910da762660c340c5447b

I tried to resolve this by removing cache files and specifying different versions etc. But, installation is always failing. 

Please let me know how I can install it on 18.04 or 20.04 versions. thanks.

**Comment by imgVOID** [comment]
You need to update your Ubuntu download pathes I think. Upgrade them via console. 
```
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
PyQt5 from 
```

**Comment by mazharoddin** [comment]
Hi, 
I tried downloading different versions for pip and python. but still, I faced the same issue with the 1.2.1 version..finally, I could able to install the 1.1.2 version.
I will try to re-install the 1.2.1 version on another machine and update the status accordingly.

**Comment by bstoilov** [comment]
I am developing mostly on Linux Mint which is based on Ubuntu 20 and have no issues what so ever.
Probably your local python cache is corrupted. I will try to reproduce it on fresh machine

**Comment by bstoilov** [comment]
Just verified it installs on fresh ubuntu 20, windows and mac

**Comment by bstoilov** [comment]
Feel free to re-open if you are still facing issues

**Comment by mazharoddin** [comment]
Sure...thanks for looking into it. I will try to recreate it on a different machine.

**Comment by bstoilov** [comment]
@mazharoddin 
It seems other people are facing similar issue. this seems to work
https://stackoverflow.com/questions/40183108/python-packages-hash-not-matching-whilst-installing-using-pip

**Comment by mazharoddin** [comment]
@bstoilov,
I tried those but it was not working, but after a few trials and errors I could able to install an older version(1.1.2), and for my requirement, the older version is working fine. 
So I will re-check once I re-installed Ubuntu 20.04. Thanks.

**Comment by mazharoddin** [comment]
Hi @bstoilov,
I re-tried installing the latest version on ubuntu 20.04 and I could able to install it without any issues. Thanks.

**Comment by bstoilov** [comment]
@mazharoddin glad you managed to sort this out :)
