### ISSUE TITLE
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.

### ISSUE THREAD

**Issue by drseu55** [bstoilov/py3-pinterest#128]
[WDM] - Current google-chrome version is 88.0.4324
[WDM] - Get LATEST driver version for 88.0.4324
[WDM] - Driver [/root/.wdm/drivers/chromedriver/linux64/88.0.4324.96/chromedriver] found in cache
Traceback (most recent call last):
  File "follow/follow.py", line 34, in <module>
    pinterest.login()
  File "/usr/local/lib/python3.6/dist-packages/py3pin/Pinterest.py", line 138, in login
    driver = webdriver.Chrome(ChromeDriverManager().install(), options=chrome_options)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

I am getting an error message when I try to run the bot on Ubuntu 18.04 VPS.

**Comment by bstoilov** [comment]
https://stackoverflow.com/questions/22424737/unknown-error-chrome-failed-to-start-exited-abnormally

Looks like a problem for linux. I am not facing it on ubuntu 20, probably for 18 there are differences.

Will investigate when I have the chance

**Comment by rhuddlestone** [comment]
I had the same problem on ubuntu 20.04 when I was using "root" user to run pinterest.login

When I used a non root user the error didn't occur.

**Comment by cr0c0pk1** [comment]
> 
> 
> I had the same problem on ubuntu 20.04 when I was using "root" user to run pinterest.login
> 
> When I used a non root user the error didn't occur.

I have tried, doesn't fix it.

**Comment by AIGeneratedUsername** [comment]
```
[WDM] - ====== WebDriver manager ======
[WDM] - Current google-chrome version is 88.0.4324
[WDM] - Get LATEST driver version for 88.0.4324
[WDM] - There is no [linux64] chromedriver for browser 88.0.4324 in cache
[WDM] - Get LATEST driver version for 88.0.4324
[WDM] - Trying to download new driver from https://chromedriver.storage.googleapis.com/88.0.4324.96/chromedriver_linux64.zip
[WDM] - Driver has been saved in cache [/root/.wdm/drivers/chromedriver/linux64/88.0.4324.96]
```


```
E       selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
E         (unknown error: DevToolsActivePort file doesn't exist)
E         (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
/usr/local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py:242: WebDriverException
```

**Comment by bstoilov** [comment]
@AIGeneratedUsername that might be cause if you run it as root, judging by stackoverflow

**Comment by jordandavis16** [comment]
I think this only affects Mac silicon users.  Chrome made some updates to the arm64 driver that ChromeDriverManager hasn't accounted for yet.  

As a short-term fix, download [chromedriver](https://chromedriver.chromium.org/downloads):

open Pinterest.py and add the following import

```shell
from selenium.webdriver.chrome.service import Service
```
Then go to line 201 and change 
```shell
driver = webdriver.Chrome(ChromeDriverManager().install(), options=chrome_options
```
to 
```shell
try:
    driver = webdriver.Chrome(ChromeDriverManager().install(), options=chrome_options
)
except:
    chromedriver_path = /path/to/your/chromedriver
    service = Service(executable_path=chromedriver_path)
    driver = webdriver.Chrome(options=chrome_options, service=service)
```
make sure to change the chromedriver path.
