### ISSUE TITLE
Log in doesn't work after design changes

### ISSUE THREAD

**Issue by SeironWP** [bstoilov/py3-pinterest#133]
Hello Folks,

Pinterest changed the Log in page design and the log in doesn't work anymore - at least for me.

I changed the Line 148 in the Pinterest.py to:

`logins = driver.find_elements_by_class_name("SignupButton")`

It's a different selenium function to find the clickable Log in button. Maybe this helps you too.

Greetings

**Comment by bstoilov** [comment]
Login is currently working
