### ISSUE TITLE
board_feed doesn't list all pins in a board.

### ISSUE THREAD

**Issue by esrefimadrabaz** [bstoilov/py3-pinterest#135]
so I've been trying to list all the pins in a board, board has 66 pins in it currently but when I try to list all of them with board_feed, I only get 14 pins. All of the pins are videos, I think it doesn't get videos that are linked to youtube or other websites. And also some of the pins doesn't even have 'videos' key in them for some reason. Can someone help me out?

**Comment by bstoilov** [comment]
There is an example on how to get all pins, pinterest pages them
https://github.com/bstoilov/py3-pinterest/blob/master/examples.py#L37
