### ISSUE TITLE
HTTPError: 401 Client Error: Unauthorized for URL

### ISSUE THREAD

**Issue by hassanaziz0012** [bstoilov/py3-pinterest#141]

**Comment by housUnus** [comment]
Same here i'm trying to repin but it tells me: 
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://www.pinterest.com/resource/RepinResource/create
Any solution please
thank you.

**Comment by murattikil** [comment]
there is a similar problem. I wonder if anyone can find a solution?

**Comment by Lymmmla** [comment]
Same problem, so I think maybe pinterest code changed? maybe it no longer applies. 
Is there anyone who pin successful?

**Comment by cijianzy** [comment]
Same problem
