### ISSUE TITLE
No attribute error if I try 'type_ahead'

### ISSUE THREAD

**Issue by mazharoddin** [bstoilov/py3-pinterest#142]
Hi,
I am trying to get some suggested keywords using 'type_ahead' method as mentioned in the documentation, but I am getting no attribute error while doing so.
Can you please let me know how to get the suggested keywords using the type_ahead method?

This is the code I am trying. 

def type_ahead(term="apple"):
    return pinterest.type_ahead(term=term)

>>> p.type_ahead("apple")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Pinterest' object has no attribute 'type_ahead'

Also, pls let me know if there is any other way I can get suggested keywords from py3-pinterest API. Thanks.

**Comment by rhuddlestone** [comment]
I think this is not a py3 problem

try 
terms = pinterest.type_ahead(term="apple")
print (terms)

this gives me result where 'apple wallpaper', 'apple crisp' etc is returned.

[{'query': 'apple wallpaper', 'type': 'query', 'url': '/search/pins/?rs=ac&len=2&q=apple+wallpaper', 'label': 'apple wallpaper', 'is_pinner': False, 'resultIndex': 0}, {'query': 'apple crisp', 'type': 'query', 'url': '/search/pins/?rs=ac&len=2&q=apple+crisp', 'label': 'apple crisp', 'is_pinner': False, 'resultIndex': 1}, {'query': 'apple pie recipe', 'type': 'query', 'url': '/search/pins/?rs=ac&len=2&q=apple+pie+recipe', 'label': 'apple pie recipe', 'is_pinner': False, 'resultIndex': 2}, {'query': 'apple watch', 'type': 'enriched_autocomplete', 'action': {'url': '/search/buyable_pins/?q=apple%20watch&rs=ac_shopping'}, 'identifier_icon_name': 1, 'label': 'apple watch', 'url': '/search/buyable_pins/?q=apple%20watch&rs=ac_shopping', 'is_pinner': False, 'resultIndex': 3}, {'query': 'apple recipes', 'type': 'query', 'url': '/search/pins/?rs=ac&len=2&q=apple+recipes', 'label': 'apple recipes', 'is_pinner': False, 'resultIndex': 4}, {'query': 'apple watch wallpaper', 'type': 'query', 'url': '/search/pins/?rs=ac&len=2&q=apple+watch+wallpaper', 'label': 'apple watch wallpaper', 'is_pinner': False, 'resultIndex': 5}, {'query': 'apple products', 'type': 'query', 'url': '/search/pins/?rs=ac&len=2&q=apple+products', 'label': 'apple products', 'is_pinner': False, 'resultIndex': 6}, {'query': 'apple pie', 'type': 'query', 'url': '/search/pins/?rs=ac&len=2&q=apple+pie', 'label': 'apple pie', 'is_pinner': False, 'resultIndex': 7}, {'first_name': '{Apple Brides}', 'full_name': '{Apple Brides}', 'id': '248894454314827825', 'image_small_url': 'https://i.pinimg.com/30x30_RS/43/49/40/434940a64824c4312a099537d85bb851.jpg', 'image_medium_url': 'https://i.pinimg.com/75x75_RS/43/49/40/434940a64824c4312a099537d85bb851.jpg', 'type': 'user', 'username': 'applebrides', 'verified_identity': {}, 'native_pin_count': 0, 'show_creator_profile': True, 'allow_mentions': 0, 'is_verified_merchant': None, 'image': 'https://i.pinimg.com/75x75_RS/43/49/40/434940a64824c4312a099537d85bb851.jpg', 'is_pinner': True, 'label': '{Apple Brides}', 'subLabel': 'applebrides', 'url': '/applebrides/', 'verified': False}, {'first_name': "Mark's Daily Apple", 'full_name': "Mark's Daily Apple", 'id': '257549809848684343', 'image_small_url': 'https://i.pinimg.com/30x30_RS/d8/a4/d6/d8a4d69e7f51d80c9bdeef74166203d7.jpg', 'image_medium_url': 'https://i.pinimg.com/75x75_RS/d8/a4/d6/d8a4d69e7f51d80c9bdeef74166203d7.jpg', 'type': 'user', 'username': 'marksdailyapple', 'verified_identity': {}, 'native_pin_count': 0, 'show_creator_profile': True, 'allow_mentions': 0, 'is_verified_merchant': None, 'image': 'https://i.pinimg.com/75x75_RS/d8/a4/d6/d8a4d69e7f51d80c9bdeef74166203d7.jpg', 'is_pinner': True, 'label': "Mark's Daily Apple", 'subLabel': 'marksdailyapple', 'url': '/marksdailyapple/', 'verified': False}, {'first_name': 'Wise Apple Vintage', 'full_name': 'Wise Apple Vintage', 'id': '225391293759488461', 'image_small_url': 'https://i.pinimg.com/30x30_RS/37/f9/87/37f987f3256ed3b12d0ecf96766e8621.jpg', 'image_medium_url': 'https://i.pinimg.com/75x75_RS/37/f9/87/37f987f3256ed3b12d0ecf96766e8621.jpg', 'type': 'user', 'username': 'wiseapplevintage', 'verified_identity': {}, 'native_pin_count': 0, 'show_creator_profile': True, 'allow_mentions': 0, 'is_verified_merchant': None, 'image': 'https://i.pinimg.com/75x75_RS/37/f9/87/37f987f3256ed3b12d0ecf96766e8621.jpg', 'is_pinner': True, 'label': 'Wise Apple Vintage', 'subLabel': 'wiseapplevintage', 'url': '/wiseapplevintage/', 'verified': False}]

**Comment by mazharoddin** [comment]
Hi @rhuddlestone,

Yes, earlier also I tried the same way as you mentioned. I omitted the initialization for simplicity. 

This is how I tried again(replaced email and password with my account details).

 pinterest = Pinterest(email='my-email',password='password',username='my-username',cred_root='cred_root')
>>> pinterest
<py3pin.Pinterest.Pinterest object at 0x7f1cc2035198>
>>> pinterest.type_ahead(term="apple")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Pinterest' object has no attribute 'type_ahead'

Can you please let me know which version you are using. Thanks.

**Comment by rhuddlestone** [comment]
Hi I am using version 1.2.2 

Try this below.  Save it as getkeywords.py then run python3 getkeywords.py apple

~$ python3 getkeywords.py apple
apple wallpaper
apple crisp
apple pie recipe
apple watch
apple recipes
apple watch wallpaper
apple products
apple pie
{Apple Brides}
Mark's Daily Apple
Wise Apple Vintage

-----------

import sys
from py3pin.Pinterest import Pinterest

pinterest = Pinterest(email='your email goes here', password='password goes here', username='look in pinterest url')

terms = pinterest.type_ahead(term=sys.argv[1])
for query in terms:
        keyword = query['label']
        print (keyword)

**Comment by mazharoddin** [comment]
Thanks for reply...I dodn't think above code will help me here,because I am getting method not found error, which is not related to the data what we are passing to it. Any way I will try to install your version and check. Thanks.

**Comment by mazharoddin** [comment]
Still seeing the same issue .. However currently I am not planning to use "type_ahead". So for now I would like to close this issue. But, I will re-open later if I face the same issue. Thanks.
