### ISSUE TITLE
No credentials stored [Errno 2] No such file or directory: 'E:\\instabot\\(myemail)'

### ISSUE THREAD

**Issue by Haiithem** [bstoilov/py3-pinterest#149]
So after I get this error after I tried to create a new instance of the API :
pinterest = Pinterest(email='(myemail)', password='(mypass)', username='(myusername)',cred_root="E:\bot")
It'd be so cool if someone can help me out.

**Comment by anuroop18** [comment]
You need to uncomment the login() function. The credentials will be stored when you login. First login() then code will work. 🐛
