### ISSUE TITLE
It uses title and description from the provided link instead of what I have provided

### ISSUE THREAD

**Issue by omi9430** [bstoilov/py3-pinterest#153]
I am using to the function upload_pin to upload new pins but I noticed one issue that is when I pass the link for outbound clicks the function uses the title and description from that link instead of the one I provided

**Comment by RedWideWeb** [comment]
Were you able to pin to board? Can you show the code? I am not able neither to pin to board nor to upload a file. Getting 400 Error Bad request

**Comment by NulledTerminator** [comment]
I am having the same issue. Using pinterest.upload_pin() the pin will upload but it imports all the data from the link instead of using the Title and Description provided in the ().

**Comment by ZenDevMaster** [comment]
I'm experiencing this as well. I'm new to this library, but in my earlier testing if no link is provided, or I something like "google.com" then Pinterest will use the supplied title/description. But now seems like it pulls from the linked url only. 

An anti-spam measure by pinterest, maybe for low-trust accounts?

**Comment by ibikhan1234** [comment]
When all the data provided for example:
Title
Description
Link

It ignores all the details and picks it from the link provided. Which means py3pin is of eventually no useful purpose.

**Comment by emarkoska** [comment]
Has anyone figured this out?

**Comment by bstoilov** [comment]
There was a problem with the title the rest is working just fine

**Comment by bstoilov** [comment]
fixed in v 1.3.0
