### ISSUE TITLE
Pin method cannt upload title

### ISSUE THREAD

**Issue by galaxyluu** [bstoilov/py3-pinterest#160]
When I use the method Pinterest.pin(board_id = boar_id, image_url = url, description = des, link = link, title = title).
After pinning, I found it impossible to enter the title field above on Pinterest.
Can you help me find where the error is.
Thanks

**Comment by NikhilMJain** [comment]
+1 Same issue.

**Comment by bstoilov** [comment]
There was a small change in the pinterest api, fixed in v 1.3.0
