### ISSUE TITLE
Make `PyQt5` an optional dependency

### ISSUE THREAD

**Issue by Amar1729** [bstoilov/py3-pinterest#166]
Some other projects use this as a dependency for communication with pinterest but don't require GUI functionality from it. Since `PyQt5` is a somewhat heavy dependency (and currently has issues installing on some ARM devices like mac M1s) can that be made an optional dependency?

Something like the following in `setup.py`:
```
setup(
    ...
    extras_require={
        "gui": ["PyQt5"],
    },
```

Then anybody wanting to use the GUI can install through pip like:
```
$ pip install 'py3-pinterest[gui]'
```

Only noticed because the default branch currently has `PyQt5` in its `setup.py` but doesn't use it anywhere yet.

**Comment by bstoilov** [comment]
Removed the dependency in version 1.3.0
