### ISSUE TITLE
250 pin limit on boards

### ISSUE THREAD

**Issue by gomme600** [bstoilov/py3-pinterest#171]
Hi,

I'm trying to download information for each pin in a board. There are over 3000 pins. When using "pins = pinterest.board_feed(board_id=board_id)" I only get 250 results. How can I get all 3000 ?

Thanks for any help

**Comment by bstoilov** [comment]
You can't fetch more than 250 it is a limitation from pinterest

to get all pins from a board use

https://github.com/bstoilov/py3-pinterest/blob/master/examples.py#L23
