### ISSUE TITLE
WebDriver login error

### ISSUE THREAD

**Issue by nizhegorodets** [bstoilov/py3-pinterest#180]
Hi! I get an error when I try to log in.  What could be the problem?

```
from py3pin.Pinterest import Pinterest

if __name__ == '__main__':
    pinterest = Pinterest(email='mail',
                          password='pass',
                          username='username')

    pinterest.login()
```

error: Failed to login 'WebDriver' object has no attribute 'find_element_by_id'

**Comment by darox** [comment]
I could fix it with
`pip install selenium==4.2.0 --force-reinstall
`
