### ISSUE TITLE
handle board sections

### ISSUE THREAD

**Issue by KristyAnon** [bstoilov/py3-pinterest#19]
Hi, Is it possible to improve this project to also handle the board sections?

If it is already supported, can you let me know how to work with them?

Thanks a lot for your great work!
Kristy

**Comment by bstoilov** [comment]
Hi I never explored this feature, I just noticed that there is such thing.

Can you elaborate more on the exact functionalities you would expect for the client to support, like create section, delete section etc.

Thanks

**Comment by KristyAnon** [comment]
Hi,
I would like to create a section, get the sections from a board, and also get the files from a section.
If you are able to make it, it would be great.
Thanks a lot!
Kristy

**Comment by bstoilov** [comment]
Hi Kristy,
the following PR: https://github.com/bstoilov/py3-pinterest/pull/20
adds support for board sections, alongside several other fixes and refactorings.

Feel free to check it out and see if there is any missing functionality or issues, I will merge it in 3 days if everything is ok.

**Comment by KristyAnon** [comment]
Hi,
Great work!! it seems to be working, I was able to get all the sections from a board, and also I was able to create a new section.
But, I was not able to get the list of pins from a section, is it possible?
Thanks,
Kristy

**Comment by bstoilov** [comment]
The get_boards function contains this data.

I didn't have to.change anything there, just wasn't aware of these sections

**Comment by KristyAnon** [comment]
with the get_boards I'm able to access to the list of sections, without issues.
Then, is it possible to get the list of pins for a section? or at least the section name on a pin? I checked and I don't think it is there.

**Comment by bstoilov** [comment]
Hi sorry you are right, to get the pins from a section you need to call
`pinterest.get_board_sections(board_id=board_id)`
in the response there is `preview_pins` array, but it seems it is limited to 10 pins.

I missed that limitation when testing, it seems there is separate endpoint which should be called to retrieve all pins from a section, I will add that and let you know.

Thanks

**Comment by bstoilov** [comment]
One more thing, the `load_pin` function response has information about the section, but it seems there is some change in the pinterest API and it is now broken, but it is a small change.
But I think calling the load_pin endpoint for each pin is a bit of a overkill and you might even get suspended.

I will work on resolving these

**Comment by bstoilov** [comment]
Hey, I was not able to find a "clean" way to retrieve the section feed. so I ended up parsing the whole html page.

So for example if I want to list pins from my section 'heels':
https://www.pinterest.com/cocococoho/s-h-o-e-s/heels/

I can now do it like this:

```
username = 'cocococoho'
board_name = 's-h-o-e-s'
section_name = 'heels'
data = pinterest.get_section_pins(username=username, board_name=board_name, section_name=section_name)
```

This can load any section in fact. If you see a way to improve this just let me know, or even better create a PR :)

**Comment by bstoilov** [comment]
The PR was merged if you still have any issues feel free to log a bug :)
