### ISSUE TITLE
Another Error on login

### ISSUE THREAD

**Issue by mic-user** [bstoilov/py3-pinterest#197]
whe call 'pinterest.login()'
occured.
`
Exception has occurred: TypeError
WebDriver.__init__() got multiple values for argument 'options'
  File "source PATH\test.py", line 17, in <module>
    pinterest.login()
TypeError: WebDriver.__init__() got multiple values for argument 'options'
`
is this still active??

**Comment by SamAmann** [comment]
Same kind of error here:
```
driver = webdriver.Chrome(
             ^^^^^^^^^^^^^^^^^
TypeError: WebDriver.__init__() got multiple values for argument 'options'
```

Wondering if still supported? (saw the last commit 2 weeks ago, I have some faith 😇)

**Comment by mic-user** [comment]
@mic-user Erm, no way to verify it since I have got official pinterest API approval.
Thanks.
Have a good day.

**Comment by SamAmann** [comment]
Good for you.

For others, I've forked the repo to check if I could do something.
When testing out, the .login() worked fine while using the local repo.
Maybe a lead?
