### ISSUE TITLE
error on get_following

### ISSUE THREAD

**Issue by elmissouri16** [bstoilov/py3-pinterest#2]
first thanks for your work 
i was just testing the functions of this module and I found a bug on  `get_following`

here is the error 

File "C:\Users\Admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\py3pin\Pinterest.py", line 231, in get_following
    self.bookmark_manager.add_bookmark(primary='following', secondary=username, bookmark=result['bookmark'])
KeyError: 'bookmark'

**Comment by bstoilov** [comment]
Hello, can you post the piece of code that is calling `get_following ` ?

**Comment by bstoilov** [comment]
I figure what might be causing this. The bookmark for the next following batch was not returned by pinterest if there were none. [Fix](https://github.com/bstoilov/py3-pinterest/commit/32c8494f5315be20f6f75077affcda51109a0915) was a simple check. 

Two more methods had the same issue, `get_comments` and `home_feed`, thanks for reporting this!

Upgrade to the latest version and see if this resolves the issue :)

**Comment by elmissouri16** [comment]
> I figure what might be causing this. The bookmark for the next following batch was not returned by pinterest if there were none. [Fix](https://github.com/bstoilov/py3-pinterest/commit/32c8494f5315be20f6f75077affcda51109a0915) was a simple check.
> 
> This affects only users with following less than 250 (which is the page size we are requesting).
> 
> Two more methods had the same issue, `get_comments` and `home_feed`, thanks for reporting this!
> 
> Upgrade to the latest version (0.1.6) and see if this resolves the issue :)

ok thank you i well test it and let you know

**Comment by elmissouri16** [comment]
> I figure what might be causing this. The bookmark for the next following batch was not returned by pinterest if there were none. [Fix](https://github.com/bstoilov/py3-pinterest/commit/32c8494f5315be20f6f75077affcda51109a0915) was a simple check.
> 
> This affects only users with following less than 250 (which is the page size we are requesting).
> 
> Two more methods had the same issue, `get_comments` and `home_feed`, thanks for reporting this!
> 
> Upgrade to the latest version (0.1.6) and see if this resolves the issue :)

that fixes the issue thank you
