### ISSUE TITLE
Create New Pin Error

### ISSUE THREAD

**Issue by MrCrap** [bstoilov/py3-pinterest#21]
I tried to make a new **PIN**, but an error.
this is my script
```
# -*- coding: utf-8 -*-
from py3pin.Pinterest import Pinterest

def test():
    username = ''
    password = ''
    email = ''

    # cred_root is the place the user sessions and cookies will be stored you should specify this to avoid permission issues
    cred_root = 'cred_root'
    pinterest = Pinterest(email=email, password=password, username=username, cred_root=cred_root)

    board_id = '854698904221395783'
    image_url = '25061712.jpg'
    description = 'description here'
    title = 'title test'
    link = 'https://pricesm.com'

    return pinterest.pin(board_id=board_id, image_url=image_url, description=description, title=title, link=link)

if __name__ == '__main__':
	test()
```
and this error occurred
```
Traceback (most recent call last):
  File "tester.py", line 22, in <module>
    test()
  File "tester.py", line 19, in test
    return pinterest.pin(board_id=board_id, image_url=image_url, description=description, title=title, link=link)
  File "/home/crabs/Documents/gameplay/py3Pinter/py3pin/Pinterest.py", line 325, in pin
    return self.post(url=PIN_RESOURCE_CREATE, data=data).json()
  File "/home/crabs/Documents/gameplay/.py3PinEnv/lib/python3.6/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
anyone can help?

**Comment by bstoilov** [comment]
Hi, the image url should be web url to image not to local file.
The json error is there because the method returns response.json() and in this case it is probably something like "not found error".
The second issue will be fixed with my pr

**Comment by bstoilov** [comment]
I will mark this as 'feature request', since pinterest supports this but it still not integrated in the script.

**Comment by MrCrap** [comment]
ok thanks..
I hope you provide a function for the upload image by path feature, like `new_pin_upload`.

**Comment by bstoilov** [comment]
Hi, this PR https://github.com/bstoilov/py3-pinterest/pull/25
enables pin local file, feel free to test it, I will probably merge this in 3 days if everything is ok

**Comment by MrCrap** [comment]
> Hi, this PR #25
> enables pin local file, feel free to test it, I will probably merge this in 3 days if everything is ok

Great work, 
I've tried, there is still an error.
please add `section_id=None` to the `pin()` function:
```
def pin(self, board_id, image_url, description='', link='', title='', section_id=None):
```

**Comment by bstoilov** [comment]
That is already there, even before the change, probably you have some local change, or some branch is not merged.
https://github.com/bstoilov/py3-pinterest/pull/25/commits/f5cbcc3b3097098965182a196cf3ede510fd47a4#diff-7725233d73b703633c5f4f0a2109ccc7L248

or am I missing something, it seems to work on my side.

**Comment by MrCrap** [comment]
yes, that was my mistake.
now it works well.
You can continue now.
