### ISSUE TITLE
I can't make the get_section_pins works

### ISSUE THREAD

**Issue by KristyAnon** [bstoilov/py3-pinterest#27]
Hi,
I tried a couple of code, but none of them are working, I get all the time the json for the board and not from the section, below is my code

```
boards = pinterest.boards(username=username)
for board in boards:
    target_board = board
    print(target_board['name'])
    
    sections = pinterest.get_board_sections(board_id=target_board['id'])
    for section in sections:
        print(section['title'] + '--' + section['slug'])

        section_pins = []
        section_pins = pinterest.get_section_pins(username=username, board_name=target_board['name'], section_name=section['slug'])
        with open("zz_" + target_board['name'] + " - " + section['slug'] + ".txt", "w") as file:
            json.dump(section_pins, file)
```

I'm doing something wrong?

Thanks,
Kristy

**Comment by bstoilov** [comment]
Hello, it no longer works on my side too..
The response object is different for some reason, this could be a change on Pinterest side.

**Comment by bstoilov** [comment]
I was able to find the request which gives section pins by section id, not sure how I missed that in the first place.
Also 'ReactBoardFeedResource' is removed from the response, that was the other issue

https://github.com/bstoilov/py3-pinterest/pull/28

It seems to work for my user, there is example I used to test it with
https://github.com/bstoilov/py3-pinterest/pull/28/commits/ecaa6975a63ced3f1e8146656b1c1826c7080f3c#diff-1210365dda97ccb4a7ecff29dffb0942

**Comment by KristyAnon** [comment]
hi, I tested the new code, and it is working as expected!
Thanks a lot

**Comment by bstoilov** [comment]
Great news! Closing the issue
