### ISSUE TITLE
pinterest.login() - error

### ISSUE THREAD

**Issue by ntdimos123** [bstoilov/py3-pinterest#29]
I am receiving the following error while executing login function

`---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
<ipython-input-29-797a05b7a100> in <module>
----> 1 pinterest.login()

C:\python\lib\site-packages\py3pin\Pinterest.py in login(self)
    116 
    117         data = self.req_builder.buildPost(options=options, source_url='/login/?referrer=home_page')
--> 118         return self.post(url=CREATE_USER_SESSION, data=data)
    119 
    120     def get_user_overview(self, username=None):

C:\python\lib\site-packages\py3pin\Pinterest.py in post(self, url, data, files, headers)
    104 
    105     def post(self, url, data=None, files=None, headers=None):
--> 106         return self.request('POST', url=url, data=data, files=files, extra_headers=headers)
    107 
    108     def login(self):

C:\python\lib\site-packages\py3pin\Pinterest.py in request(self, method, url, data, files, extra_headers)
     96 
     97         response = self.http.request(method, url, data=data, headers=headers, files=files, proxies=self.proxies)
---> 98         response.raise_for_status()
     99         self.registry.update(Registry.Key.COOKIES, response.cookies)
    100         return response

C:\python\lib\site-packages\requests\models.py in raise_for_status(self)
    938 
    939         if http_error_msg:
--> 940             raise HTTPError(http_error_msg, response=self)
    941 
    942     def close(self):

HTTPError: 401 Client Error: Unauthorized for url: https://www.pinterest.com/resource/UserSessionResource/create/`

**Comment by bstoilov** [comment]
401 is usually wrong credentials.
How do you typically log in to pinterest?
Do you type in the credentials or use the other options, this client can work only with the typed in username and passoword

**Comment by knsrky** [comment]
same problem for me. some accounts can log in successfully and send pins. however, some accounts cannot log in and receive the same 401 error. I'm sure the credentials are correct, I was able to log in with the browser.
Thank you!

**Comment by bstoilov** [comment]
Can some one send the response from the login. There could be some hint there

**Comment by knsrky** [comment]
ok, my mistake.. when trying login from another location, pinterest gives suspicious login error. may be this error can handle but code is clean :) thank you

**Comment by Gmanicus** [comment]
Hey, I thought it would be silly to create a new issue for this. Just a suggestion to avoid... people like me having issues I guess? Lol.

Anyway, somewhat related: In the examples.py file you comment out pinterest.login() with the statement that it would store/obtain cookies. This made it seem like it was unnecessary unless you wanted to mess with cookies. Not sure how I came to that conclusion, but if you would simply uncomment that line, I'm sure it would help people like me from getting confused. Thanks!

**Comment by bstoilov** [comment]
Thank you @Gmanicus that is a good suggestion, you can make a PR for it, other wise I will make it after some time :)

**Comment by bstoilov** [comment]
Documentation was updated feel free to open another issue in case there are problems
