### ISSUE TITLE
Pin function strips whitespace?

### ISSUE THREAD

**Issue by ExoCode17** [bstoilov/py3-pinterest#3]
Hi there! I am trying to work with your repository from a couple of days but I am having some trouble with the pin titles.

I am using bs4 to get the title of a webpage to use as the pin title. The variable displays correctly when printed, but as soon as I pass it to the pin function all of the white spaces are removed when I look at the board on Pinterest.

Any idea why is this happening? Can you look at my code and help me figure it out?

**Comment by bstoilov** [comment]
Hello, I noticed this problem once or twice but eventually it went away, probably it is some corner case, can you give me the piece of code you are using to pin?

**Comment by ExoCode17** [comment]
It actually did it on 500+ pins with no exception. The title-grabbing function is ok, tested multiple times.

It's strange it did it only once or twice on your end, as I noticed this on lines 10-18 of RequestBuilder.py:

```
def buildPost(self, options, source_url, context={}):
        return self.url_encode({
            'source_url': source_url,
            'data': json.dumps({
                'options': options,
                "context": context
            }).replace(' ', ''),
            '_': '%s' % int(time.time() * 1000)
        })
```

I changed the replace with a full whitespace. I just run the script on 1000+ pins and it worked without a single error, adding all the necessary spaces to ALL pins.

**Comment by bstoilov** [comment]
Great! Nice catch, I haven't set up collaborators on the repo yet, so I will apply your fix and push the new version :)

**Comment by ExoCode17** [comment]
Great, but I was wandering if it would break other things. Why was it
removing that whitespace in the first place?

**Comment by bstoilov** [comment]
I will test it on my end, there was some reason for this for sure.

**Comment by ExoCode17** [comment]
Please let me know your findings!
*Flygohr - Gabriele Pezzin*
*Freelance Comic Book Artist and Illustrator*
info@flygohr.com / www.flygohr.com

From Trento, Italy

**Comment by bstoilov** [comment]
It appears that the whole replace was a left over from other issue. I have removed it entirely and all the f unctions are working as expected.

The new version 0.2.3 is published let me know if you still have the issue.

**Comment by ExoCode17** [comment]
I'll update it and see if it works as soon as I get back to my workstation.
I'll let you know!

**Comment by ExoCode17** [comment]
Yep, it's working out of the box! Just tried the pin function tho, no need for others atm

**Comment by bstoilov** [comment]
Great closing the issue
