### ISSUE TITLE
Limits for Search Results

### ISSUE THREAD

**Issue by ReichYang** [bstoilov/py3-pinterest#31]
Hi there. Just wondering what is the limits for the results returned by searching pins with keywords. I've tried to remove the max_iteration in the example code and it could only give me 1076 results no matter what query I put in. Thus, is this API only retrieves the top 1076 results for searching?

**Comment by bstoilov** [comment]
Does it aleays return max 1076 results, or only for that specific query

**Comment by ReichYang** [comment]
I‘ve tried several queries, and the results are around 1076 or 1086.

**Comment by bstoilov** [comment]
The API returns what Pinterest would return, I also see the same behaviour with my account, I will need to test with the Pinterest UI and see if the results are the same.

**Comment by bstoilov** [comment]
Looks like limitations are coming from pinterest.
