### ISSUE TITLE
Add url to a pin

### ISSUE THREAD

**Issue by tung-nguyen-uet** [bstoilov/py3-pinterest#35]
Hi,
Thank you very much for porting it to python3.
I have a feature request.
Could you add url besides image_url to pinterest.pin()?
As you might know, when user create a pin, they can link an url to it.

Regards,

**Comment by bstoilov** [comment]
Hi, not sure If I get this

The regular pin method has this signature
`pin(self, board_id, image_url, description='', link='', title='', section_id=None)`
`image_url` is web address of the image
`link` is the url you want to specify to which users are directed upon clicking

The upload_pin:
`upload_pin(self, board_id, image_file, description='', link='', title='', section_id=None)`
`image_file` is local file path to the image
`link` is the same thing as with `pin`

There is an issue regarding the lack of documentation.
https://github.com/bstoilov/py3-pinterest/issues/15

**Comment by vietrap91** [comment]
> Hi,
> Thank you very much for porting it to python3.
> I have a feature request.
> Could you add url besides image_url to pinterest.pin()?
> As you might know, when user create a pin, they can link an url to it.
> 
> Regards,

bạn Tùng có Facebook không cho mình hỏi xíu.

**Comment by bstoilov** [comment]
Closing this as it seems the issue is resolved :)
