### ISSUE TITLE
Pinterest Private proxy login ? 

### ISSUE THREAD

**Issue by echoyilmaz** [bstoilov/py3-pinterest#36]
My English is bad :)

I manage multiple pinterest accounts. I want to login using private proxy. Private proxy authentication need. If you provide a sample code blog, I'll solve it immediately.

**Comment by echoyilmaz** [comment]
Here's how I solved my problem.

`from py3pin.Pinterest import Pinterest



username = 'lum-customer-hl_18949a2b-zone-pinterest-ip-69.16*.*.*'
password = 'password'
port = 22225
session_id = random.random()
super_proxy_url = ('http://%s-session-%s:%s@zproxy.lum-superproxy.io:%d' %
    (username, session_id, password, port))


proxies = {
  "http": super_proxy_url,
  "https": super_proxy_url
}

pinterest = Pinterest(email='email@yandex.com',
                      password='pass',
                      proxies=proxies,
                      username='username',
                      cred_root='cred_root')

logged_in = pinterest.login()`

**Comment by bstoilov** [comment]
That is great, do you want to add this in examples.py? As separate fucntion so other user can reuse it

**Comment by echoyilmaz** [comment]
> 
> 
> That is great, do you want to add this in examples.py? As separate fucntion so other user can reuse it

Yes of course :)

**Comment by bstoilov** [comment]
Proxy usage has been documented.
