### ISSUE TITLE
429 Client Error: Too Many Requests for url

### ISSUE THREAD

**Issue by Gmanicus** [bstoilov/py3-pinterest#37]
Hi,

Getting close to the completion of a project using the py3-pinterest library. Forgot to disable a function that was creating a test pin, and I ended up creating a pin every time a ran a test. Not too big a deal. Created like 30 pins over a few hours.

Anyway, it was made evident that I forgot that function when I started getting the 429 client error. I see there is there is a rate limit in the Pinterest API. It's 10 actions per hour per unique user for apps that haven't been approved.

I take it py3-pinterest is limiting to 10 per hour? Is there anything I can do to keep the issue from happening when I finish the project? I'd like to avoid getting rate-limited if possible. I expect anywhere from 1-10 per hour for now. More if my project ends up getting used a lot.

**Comment by bstoilov** [comment]
Those limitations are probably for the official pinterest API. I haven't found limits for the UI, but there should be some.

We could store all activity per user in file, for example in json format. And then each time we perform request with the py3-pinterest check and update that file.

**Comment by Gmanicus** [comment]
And then if a user hits the rate limit, switch to another user?

**Comment by Gmanicus** [comment]
Further testing has led me to the fact that it isn't 10 general actions, thankfully. It appears to be limiting me to 10 actions per link, hour, and user. So, I can create 10 boards, 10 pins, and etc in one hour.

In my use case, all the pins need to be made on a single user, so I'll just detect when I hit the rate limit. When I do, I'll store all the data I'm being given and then pin it when the limit has been lifted.

**Comment by LinkTree3** [comment]
Hi! I just started using py3-pinterest and started to get 429 errors for too many requests. I wanted to know if any of you found out what are the rate limits for uploading pins?

Thank you!
