### ISSUE TITLE
404 Client Error

### ISSUE THREAD

**Issue by yusufulusoy** [bstoilov/py3-pinterest#4]
Hello,

Whenever I try to send a pin with pin() I get an error:

`requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.pinterest.com/resource/PinResource/create/`

How can I fix it?

**Comment by bstoilov** [comment]
Hey, do you still have any issues?

**Comment by yusufulusoy** [comment]
@bstoilov Hi, working but I don't understand sometimes has failed as 403 and 404 errors. I changed pinterest account may be account authentication problem.

**Comment by bstoilov** [comment]
Try deleting the credentials folder, that will force new login with new sessions. I never had your issue let me know if you figure out when it happens

**Comment by selene-y** [comment]
@bstoilov Hello, I got the same error here, here is the error message:
```
Exception has occurred: HTTPError
404 Client Error: Not Found for url: https://www.pinterest.com/resource/PinResource/create/
```
Here is my code:
```
def pin(board_id='',
        section_id=None,
        image_url='https://i.pinimg.com/564x/cb/ae/c1/cbaec1bb42b0a38c2eecbd69af8d1678.jpg',
        description='this is auto pin',
        title='a bot did this',
        link='https://www.google.com/'):
    return pinterest.pin(board_id=board_id, section_id=section_id, image_url=image_url,
                         description=description, title=title, link=link)
```
I have deleted the credentials folder and it doesn't work.
Besides, I have try creating a pin on website and it is successful.
How can I fix it?

**Comment by TianboZ** [comment]
Hello @bstoilov I got the same error now, my Pinterest account is email + password, not facebook or google account. I can successfully call pinterest.login(). But when I try to create a pin, I got above error.

**Comment by pkxianjian** [comment]
I get the same error,i can get the board message ,but can't pin.

**Comment by pkxianjian** [comment]
> @bstoilov Hello, I got the same error here, here is the error message:
> 
> ```
> Exception has occurred: HTTPError
> 404 Client Error: Not Found for url: https://www.pinterest.com/resource/PinResource/create/
> ```
> 
> Here is my code:
> 
> ```
> def pin(board_id='',
>         section_id=None,
>         image_url='https://i.pinimg.com/564x/cb/ae/c1/cbaec1bb42b0a38c2eecbd69af8d1678.jpg',
>         description='this is auto pin',
>         title='a bot did this',
>         link='https://www.google.com/'):
>     return pinterest.pin(board_id=board_id, section_id=section_id, image_url=image_url,
>                          description=description, title=title, link=link)
> ```
> 
> I have deleted the credentials folder and it doesn't work.
> Besides, I have try creating a pin on website and it is successful.
> How can I fix it?

your board_id is empty,you should get your board_id first
