### ISSUE TITLE
Return Board, Section, Pin ID upon creation

### ISSUE THREAD

**Issue by Gmanicus** [bstoilov/py3-pinterest#40]
Hi,

I'm currently having to scout the requests on Pinterest manually to find the IDs for Boards, Sections, and Pins. The ID comes directly in the response data from the POST request for each of these actions, so I would like to request that it be included in the returned data from those functions. Right now, I believe they just return request response codes.

I will see if I can do it myself in the meantime, and I'll make a pull request if I get it working without any major changes.

**Comment by bstoilov** [comment]
Good suggestion. The examples should be updated too.
The create  board actually returns the full response object

`return self.post(url=CREATE_BOARD_RESOURCE, data=data)`

Initially I had custom object that contained only the meaningful information from the responses, but it was hard to maintain

**Comment by Gmanicus** [comment]
Another note upon further use of this method:

Section and Board IDs are one step further down the dict. It may be the same for Pins too.
```py
id = response["resource_response"]["data"]["id"]
```

**Comment by bstoilov** [comment]
Thank you very much Gmanicus, we should add these to the documentation.

**Comment by Gmanicus** [comment]
Created PR #43
