### ISSUE TITLE
Create Boards Unauthorized for url error ?

### ISSUE THREAD

**Issue by echoyilmaz** [bstoilov/py3-pinterest#41]
Hi,
No matter how much I try, I can't create a board. I get the same error with several different users.

Python code:

```
from py3pin.Pinterest import Pinterest
import random,os,pickle


username = 'lum-customer-hl_18949a2b-zone-********'
password = 'passwords'
port = 22225
session_id = random.random()
super_proxy_url = ('http://%s-session-%s:%s@zproxy.lum-superproxy.io:%d' %
    (username, session_id, password, port))


proxies = {
  "http": super_proxy_url,
  "https": super_proxy_url
}

pinterest = Pinterest(email='email@yandex.com',
                      password='Judgenie!5145',
                      proxies=proxies,
                      username='userurl',
                      cred_root='cred_root')

logged_in = pinterest.login

boards = pinterest.boards()

for i in boards:
    print(i['name'])
    print(i['id'])

boardadd = pinterest.create_board('Design', 'Design')
```

Error code:
`Traceback (most recent call last):
  File "C:\Users\****\Desktop\pint\pinterest1.py", line 34, in <module>
    boardadd = pinterest.create_board('Design', 'Design')
  File "C:\Users\****\AppData\Local\Programs\Python\Python37-32\lib\site-packages\py3pin\Pinterest.py", line 177, in create_board
    return self.post(url=CREATE_BOARD_RESOURCE, data=data)
  File "C:\Users\****\AppData\Local\Programs\Python\Python37-32\lib\site-packages\py3pin\Pinterest.py", line 110, in post
    return self.request('POST', url=url, data=data, files=files, extra_headers=headers)
  File "C:\Users\****\AppData\Local\Programs\Python\Python37-32\lib\site-packages\py3pin\Pinterest.py", line 102, in request
    response.raise_for_status()
  File "C:\Users\****\AppData\Local\Programs\Python\Python37-32\lib\site-packages\requests\models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://www.pinterest.com/resource/BoardResource/create/`

**Comment by Gmanicus** [comment]
Perhaps the issue lies in `logged_in = pinterest.login`? Although, if that was actually not correct, I would think it would fail on `boards = pinterest.boards()` as well.

I was having this issue when trying to set a category for a board as well. Pinterest has different names for some of the labels that you will see in the Pinterest search bar. The one for Design just happens to be "design", although lowercase. Not sure if Pinterest's API is strict on the casing.

**Comment by echoyilmaz** [comment]
> 
> 
> I assume you actually have it as `logged_in = pinterest.login()`? Otherwise, it shouldn't work as `logged_in = pinterest.login`
> 
> I was getting the 401 response when trying to set a category incorrectly. Pinterest has different names for some of the labels that you will see in the Pinterest search bar. The one for Design just happens to be "design", although lowercase. Not sure if Pinterest's API is strict on the casing, but I would give that a try.



-- | --

**Comment by echoyilmaz** [comment]
You are right :) I mixed things up  logged_in = pinterest.login() no error when you make. Thank you so much
