### ISSUE TITLE
Traceback issue

### ISSUE THREAD

**Issue by bapaero** [bstoilov/py3-pinterest#44]
Hi, 
I have a issue with the download_board_image.py, when i type the command:
python3 download_board_images.py
he show me the error ::
Traceback (most recent call last):
  File "download_board_images.py", line 39, in <module>
    url = pin['image']
KeyError: 'image'

I am dont understand what is the problem ...

Thank in advance to your help

**Comment by bstoilov** [comment]
Hello, it seems the example was outdated, sorry about that, the method is returning the actual object from pinterest, so to obtain the url you need

`url = pin['images']['orig']['url']`

I will update this shortly
