### ISSUE TITLE
board follow and user follow NOT working

### ISSUE THREAD

**Issue by bho9668** [bstoilov/py3-pinterest#46]
Hi I have tried out the example python scripts.
Although I could successfully logged in and pull up board ids and user ids from the script,
when the script run the "follow" methods, it will ends up with exception errors.

Does anyone successfully use the follow method? maybe Pinterest has changed their API?

**Comment by bstoilov** [comment]
Can you post the exception?

**Comment by EJS00102** [comment]
Have you guys managed to fix this?
![image](https://user-images.githubusercontent.com/52255287/78331383-372d3b00-7586-11ea-9eb0-5009a6575e1a.png)

**Comment by bstoilov** [comment]
@EJS00102 this could be because you are already following the user.
@bho9668 I just tested both user follow and board follow calls and they are working on my side.

```
# Follow some random board and user
pinterest.follow_user(user_id="720013196584364327")
pinterest.follow_board(board_id="720013127864985829")
```

**Comment by bstoilov** [comment]
Closing this, if you are still facing issues feel free to re-open or open new issue
