### ISSUE TITLE
pinterest.login() causes the following error !

### ISSUE THREAD

**Issue by ShakirKhurshid** [bstoilov/py3-pinterest#48]
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://www.pinterest.com/resource/UserSessionResource/create/

**Comment by bstoilov** [comment]
This can be caused either by too many invocations of the login method, or if you are running old version of the client.

**Comment by ShakirKhurshid** [comment]
Is there some way i can check the condition whether i am logged in , if yes then don't run the login() method .

**Comment by ShakirKhurshid** [comment]
Moreover i wanted to ask you , how to get the pin id of a pin i ve uploaded

**Comment by bstoilov** [comment]
Once you login, the session is valid for several days, so you can log in every other day for example, I was not able to implement something smarter.

As for the pinId it is inside the response returned from the method, it is actually the raw response from pinterest.

**Comment by bstoilov** [comment]
Hello, are you still facing any issues with this?
