### ISSUE TITLE
Issue while creating new pin

### ISSUE THREAD

**Issue by geetanshjindal** [bstoilov/py3-pinterest#5]
Hi,
First of all, thank you for all the hard work you've put in. 

I am trying to create a new pin in an already created board. getting the following error.

**Environment:**
OS: Linux / 64bit
Python : 3.7

**Forbidden for url: https://www.pinterest.com/resource/PinResource/create/**

Traceback (most recent call last):
  File "modules/destination/pin_terest.py", line 24, in <module>
    abc = pin()
  File "modules/destination/pin_terest.py", line 21, in pin
    return pinterest.pin(board_id=board_id, image_url=image_url, description=description, title=title, link=link)
  File "/home/g/anaconda3/envs/pinterest_bot/lib/python3.7/site-packages/py3pin/Pinterest.py", line 321, in pin
    return self.post(url=PIN_RESOURCE_CREATE, data=data).json()
  File "/home/g/anaconda3/envs/pinterest_bot/lib/python3.7/site-packages/py3pin/Pinterest.py", line 104, in post
    return self.request('POST', url=url, data=data, files=files)
  File "/home/g/anaconda3/envs/pinterest_bot/lib/python3.7/site-packages/py3pin/Pinterest.py", line 96, in request
    response.raise_for_status()
  File "/home/g/anaconda3/envs/pinterest_bot/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://www.pinterest.com/resource/PinResource/create/

**Comment by bstoilov** [comment]
Hey
make sure you have rights to pin to the board
double check that you are providing your correct username

If those are ok, can you give me the line on which you are calling the pin method
are you using it like this:

```
board_id = 'board_id'
image_url = 'image url'
description = 'this is auto pin'
title = 'a bot did this'
link = 'https://www.google.com/'
pinterest.pin(board_id=board_id, image_url=image_url, description=description, title=title, link=link)
```

**Comment by geetanshjindal** [comment]
I have cross checked my credentials, they are correct. 

below if my code:
```

from py3pin.Pinterest import Pinterest

username = 'my_username' # (copied from profile url)
password = 'my_password'
email = 'email@example.com'
cred_root = 'cred_root'

pinterest = Pinterest(email=email,
                      password=password,
                      username=username,
                      cred_root=cred_root)

def pin():
    board_id = 'test' #created  board manually on  pinterest  by the name of test
    image_url = 'https://www.tineye.com/images/imageurl-firefox.png'
    description = 'this is auto pin'
    title = 'a bot did this'
    link = 'https://www.google.com/'
    
return pinterest.pin(board_id=board_id, image_url=image_url, description=description, title=title, link=link)
```

**Comment by bstoilov** [comment]
board_id should be the id of the board no the name

use `pinterest.boards()` to get the id of  the board with name 'test' and then use the id.

I could add get board by name and use it internally in such cases

**Comment by geetanshjindal** [comment]
Thanks man, it worked.
that was really helpful of you.
kudos

**Comment by bstoilov** [comment]
No problem :) Open new issues if you have more problems. I will close this one

**Comment by EssadikElmangoug** [comment]
> board_id should be the id of the board no the name
> 
> use `pinterest.boards()` to get the id of the board with name 'test' and then use the id.
> 
> I could add get board by name and use it internally in such cases

Hey, I've coded a get_board_id method, if anyone interested in working with it. Thanks for your efforts man!
