### ISSUE TITLE
upload_pin freeze

### ISSUE THREAD

**Issue by zivlakmilos** [bstoilov/py3-pinterest#51]
I try to make software for uploading 1-3 pins every couple of minutes to Pinterest.
At the beginning I authenticate to Pinterest, upload 1-3 pins and that work correctly.
After sleep of couple minutes when script try to upload other 1-3 pins first call to upload_pin freeze and never return from call.

**Comment by bstoilov** [comment]
Can you post your code?

**Comment by zivlakmilos** [comment]
I surround uploadin_pin call with try catch and now I getting following error.
`HTTPSConnectionPool(host='www.pinterest.com', port=443): Read timed out. (read timeout=None)
`

Now I try to upload one image every couple of minute, and every second or third time I getting timeout error.
I call auth once at script start, and later call upload method of class Uplaoder.

`class Uploader:
    def __init__(self):
        self._pinterest = None

    def auth(self, email, password, username):
        self._pinterest = Pinterest(email = email, password = password, username = username, cred_root = './config')
        self._pinterest.login()
        try:
            user_profile = self._pinterest.get_user_overview()
        except HTTPError as e:
            self._pinterest.login()
            try:
                user_profile = self._pinterest.get_user_overview()
            except HTTPError as ex:
                print(ex)

    def uploadImage(self, boardId, image):
        try:
            pinResponse = self._pinterest.upload_pin(board_id = boardId,
                                                     section_id = None,
                                                     image_file = image.getFilePath(),
                                                     description = image.getDescription(),
                                                     title = image.getTitle(),
                                                     link = image.getLink())
            print(pinResponse)

            return True
        except ReadTimeout as e:
            print(e)
        except HTTPError as e:
            print(e)

        return False

    def getBoards(self, username):
        return self._pinterest.boards(username = username)`

**Comment by traint** [comment]
A similar problem. At first everything works fine, but then the pins stop being created
Here is the piece of code responsible for this

i = 1
while i < len(link_list):
    link = link_list[i]
    image = image_list[i]
    title = title_list[i]
    print(link, image, title, sep=' ')
    try:
        pin = pinterest.pin(
                            board_id= board,
                            image_url = image,
                            description = title,
                            title = title,
                            link = link)
        print('COOL!!')
    except:
        print('FOO!!')
        pass
    i += 1
    time.sleep(randint(60,120))

**Comment by bstoilov** [comment]
Are you by any change using proxies?

**Comment by traint** [comment]
No, I don't use proxies

**Comment by zivlakmilos** [comment]
No. Me nether.

**Comment by bstoilov** [comment]
To me it seems, these are random outages by Pinterest, it could be also you had pinned too much and they have some sort of protection. Try to stay below 50-60 pins a day per account. And max 5 accounts per IP. That should be safe enough. 
Also keep in mind that new and small accounts are more likely to be locked, once the account get around 10k followers and its 6+ months older it will be less likely to get locked
