### ISSUE TITLE
pin of video?

### ISSUE THREAD

**Issue by isdito** [bstoilov/py3-pinterest#53]
hello

If I will like post a pin of youtube video?

reggards

**Comment by bstoilov** [comment]
Can you tell me where is this feature in the pinterest UI? I need to see how they are doing it before it can be automated in the code

**Comment by KristyAnon** [comment]
I don't pinterest support videos

**Comment by bstoilov** [comment]
Hello, quick update on this. In order to upload videos you need business account.
py3-pinterest doesn't support business accounts
