### ISSUE TITLE
Pin issue description & link

### ISSUE THREAD

**Issue by Asteur** [bstoilov/py3-pinterest#57]
Hi!
Thanks for the workaround. 
I got an issue when uploading pin
`p.upload_pin(board_id='1111', image_file="pathtoimage/img.jpg", description='blabla #test #test2', link='linktohtmlpage', title='title', section_id=None)`
Everything is ok, except that description is text from link, and provided description is ignored. Any thoughts?

_Updated_

I checked `p.pin` method with `image_url` the same here

**Comment by bstoilov** [comment]
I can't reproduce this with my account. Seems to be working.

Can you make sure you are using the latest version of the library?
