### ISSUE TITLE
pin id, board id

### ISSUE THREAD

**Issue by goldencoder20** [bstoilov/py3-pinterest#58]
hello sir

where can I find a pin id and board id ?

**Comment by bstoilov** [comment]
To find a board id, you need to list all board of a user and chose one:

```
the_first_board = pinterest.boards_all(username=username)[0]
board_id = the_first_board['id']
```

To get pin id you need to search for it some how
You can use `board_feed` to get all pins of a board or `search` to search for pins by some phrase.
But I find it more convenient to just get it from pinterest
If you open a pin and check the url it will look like this
https://www.pinterest.com/pin/700239442053501777/

`700239442053501777` is actually the pin id

**Comment by goldencoder20** [comment]
thanks a lot
