### ISSUE TITLE
Description of Documentation of the Pin Data?

### ISSUE THREAD

**Issue by ReichYang** [bstoilov/py3-pinterest#59]
Hi there! Thanks for the work at first.
I just have a question about the data. The pin data returned have "repin count" field and there is an "aggregated data" column where there is "saves" count. What's the difference? In Pinterest's instruction (https://help.pinterest.com/en/business/article/pin-stats), a save equals a repin. However, the repin count and the saves count is drastically different for each pin I retrieved. 

And the aggregated stats have a key called "done", which is also confusing?

Thanks in advance.

**Comment by bstoilov** [comment]
Hi, the repin should be ignored, they use saves in their UI. It was called repin some years ago. Not sure what is incrementing the repin count now.
