### ISSUE TITLE
Various HTTP Errors

### ISSUE THREAD

**Issue by abundat-david** [bstoilov/py3-pinterest#6]
Thank you for this script! I have tried rewriting other Pinterest libraries to be python3 compatible, but this is far more robust.

I am using this at smallish scale (testing with ~10 accounts) and have come across a few different HTTP Errors:

`requests.exceptions.HTTPError: 404 Client Error: Not Found for url`
`requests.exceptions.HTTPError: 403 Client Error: Forbidden for url`
`requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url`

The credentials to the accounts are correct and have had library functions properly working before. 

Are these errors happening because multiple accounts are being used by this script? Is there a way to better debug these errors on the accounts the library is failing on occasionally?

Thanks!

**Comment by bstoilov** [comment]
The 404 and 403 can be caused by lots of things i will need code examples to figure it out.
The too many requests is caused because you are.violationg pinterest limits. Are you using proxies for each of these 10 account?

**Comment by bstoilov** [comment]
There is a limit on the maximum requests per minute you can make per ip not sure what is. it but with 10 account it is probably easy to reach it.
 if you can give me example for repin that returns.error code I might be able to help

**Comment by abundat-david** [comment]
Thanks for the help! Each account is put on a separate process with every account's info passing as an argument.

Here is the process that handles repins:
`  email = config['email']
    passw = config['pass']
    username = config['username']
    pinterest = Pinterest(username=username, email=email, password=passw, cred_root='cred_root')

    boards = pinterest.boards()

    maxPins = len(min(pics, key=lambda coll: len(coll)))

    count = 0

    for i in range(0, maxPins):

        try:
            boardpics = [p[i] for p in pics]

            for pic in boardpics:
                app.logger.info('starting pin_scheduler')
                picture = pic.split('/')[-1]
                boardname = helpers.extract_board_name(picture=picture)
                pin = picture.split(boardname)[1][1:]

                board_id = next((b['id'] for b in boards if boardname == b['name']), '')

                try:
                    app.logger.info("The picture %s is repinned as pin %s to board %s with id %s for email %s", repr(picture), repr(pin), repr(boardname), repr(board_id), config['email'])
                    pinterest.repin(board_id=boar_id, pin_id=pin)
                    count += 1
                    app.logger.info("Current counter is: " + str(count))
                except:
                    traceback.print_exc()
                    app.logger.info('couldnt repin using scheduler')
        except Exception as e:
            app.logger.info(e)`

I store pin_ids in a database which also includes which board is best suited for the pin. `pics` is a list of lists where each sub list contains contents for a specific board retrieved from the DB.  

Also do you have any recommendations on the best way to keeping this API up to date? I originally was using cvhau's version (converted it to python3) for a while until last week nothing worked. Your implementation has been working much better!

**Comment by abundat-david** [comment]
Hey @bstoilov, just wanted to follow up to see if you were able look more into the 404/403 issues?

**Comment by bstoilov** [comment]
Hey I will take a look today, I didn't have access to computer
One more thing the reoin never works or it sometimes work?

**Comment by abundat-david** [comment]
No problem! It sometimes works - and when it works and when it doesnt seems pretty random. I can try to get more logging into my program though to see if there is a pattern. The pins where the repin fails though are definitely valid.

Also temporarily, instead of using proxies I have scheduled each account to start posting an hour apart from each other to see if that reduces any issues. They still seem to persist though so I will be trying proxies soon.

Another thing I was going to try was to have the accounts cred root folder refreshed every day or so.

**Comment by bstoilov** [comment]
Hello I had the time to look at you code.

There are some things that might be causing issues like

`boar_id` if this is not the id of a board that the user owns or is allowed to pin to, you will get 403 Forbidden error. Track one of the failing requests and double check that particular user own the board.

The 404 Not Found error is probably coming from the fact that you are using non existing pin id, or again pin ids that the user has no rights to view. (private pins), can you double check this also?

What is `pin` object, you are passing it to the repin function, it should be pin id from pinterest.

I will give you and example with one of my boards:
I will repin this pin https://www.pinterest.com/pin/310044755598496477/
the pin id is `310044755598496477`

to this board 
https://www.pinterest.com/cocococoho/beautiful-and-breathtaking-places/

Using `boards = pinterest.boards()` I get the board id, which in this case is `547539335885628672`

Now I have everything 
`pinterest.repin(board_id='547539335885628672', pin_id='310044755598496477')`

Note how I am passing them as strings, that is the way pinterest expects them.

And you can see I have repined it https://www.pinterest.com/pin/547539267197198351/

The repin functionality is renamed to save in the pinterest UI.


One more thing that seems a bit odd, in your code you are dealing with pictures, are you using existing pins and want to **repin** them of you have pictures and you want to **pin** them?
If you have local pictures on your computer and want to pin them, this functionality is still not integrated, you can create an issues with feature request label for this.
If you are storing image urls, then you can easily pin them.

**Comment by abundat-david** [comment]
The existence / privacy of pins could definitely be an issue - I will look into this. I gather pins to store in the database from a while ago and will only repin when all of them are used. Is there a way to check the privacy of a pin when using the search function? 

`pin` in this case is the the `pin_id` we store pins as [boardname]_[pin_id] in our database which is the reason why there is extra logic.

`picture` is just a name of a variable, it does not have any significance to an actual picture. Everything thats either uploaded or repinned is url based.

Thanks for the help - I will keep you updated on my progress!

**Comment by abundat-david** [comment]
@bstoilov made some more headway and confirmed all pins / board permissions were OK. The main thing I caught (and I recommend updating the read me for this to be more clear) was that I was not getting the full list of board names for some clients. Since boards are only given in batches of 50 and I was only calling the method once, the board name I was trying to repin to didn't match any boards I was gathering. This was especially a problem to users with over 100 boards.

A quick loop fixed this:
`
batch_boards = pinterest.boards()
boards = []
while batch_boards != []:
    boards += batch_boards
    batch_boards = pinterest.boards()
`

**Comment by bstoilov** [comment]
Hello, it is good that you resolved this, was this the only issue?

All endpoints that list resources like boards pins etc, work tha same way, with batches, this comes from pinterest.
You are right the readme is a bit missleading, I will update it.

**Comment by bstoilov** [comment]
Hi , i updated readme and the examples.py file.

If you still face any issues feel free to reopen this.
