### ISSUE TITLE
How to we use proxy

### ISSUE THREAD

**Issue by akayhanlar** [bstoilov/py3-pinterest#60]
I see in Pinterest.py is proxies=None. But I want to use proxy, how to use it?

**Comment by liutianfang** [comment]
sock5 proxy, add follow code at beginning of the program:

`import socket
import socks

socks.set_default_proxy(socks.SOCKS5, "127.0.0.1", 1080)
socket.socket = socks.socksocket`

**Comment by adem74** [comment]
how can we use username and password?

**Comment by bstoilov** [comment]
@liutianfang  thanks didn't know you can do that.

@adem74 the easiest way to setup proxy is:

`proxies = {"http":"http://username:password@proxy_ip:proxy_port"}`

and then upon creating the pinterest class just pass them like so:

`pinterest = Pinterest(email='email', password='pass', username='name', cred_root='cred_root', proxies=proxies)`

I will include this into the documentation and examples.

Feel free to re-open the issue if you are still facing issues
