### ISSUE TITLE
load_pin(), doesn't work

### ISSUE THREAD

**Issue by liutianfang** [bstoilov/py3-pinterest#61]
I want use comment pin function pinterest.comment, but load_pin() has follow error:

  File "\py3-pinterest\py3pin\Pinterest.py", line 330, in load_pin
    return pin_data['resourceResponses'][0]['response']['data']
KeyError: 'resourceResponses'

**Comment by liutianfang** [comment]
modify Pinterest.py line330 ，change to       :

  return pin_data['pins'][str(pin_id)]

**Comment by liutianfang** [comment]
modify Pinterest.py line324 ，change to :
        soup = BeautifulSoup(resp.text, 'html5lib')

html.parser doesn't work here,  use html5lib. You need pip install html5lib

**Comment by bstoilov** [comment]
This fix is included in release-1.1.0

Thanks!
