### ISSUE TITLE
get_board_sections only returns the first 25 sections

### ISSUE THREAD

**Issue by KristyAnon** [bstoilov/py3-pinterest#66]
Hi,
I'm trying to get the list of sections from a board that has 55 sections, and the get_board_sections only returns the first 25.
Is it possible to get them all?

Thanks,
Kristy

**Comment by bstoilov** [comment]
Similar issue has just been fixed with get board section pins

https://github.com/bstoilov/py3-pinterest/pull/65

We have to do the same for this function as well

**Comment by imgVOID** [comment]
I've made fix, see pull requests.

**Comment by bstoilov** [comment]
This is now included in the latest release, please update you version.

Thanks @imgVOID
