### ISSUE TITLE
Better Appreach of  Saving The registry.dat

### ISSUE THREAD

**Issue by elmissouri16** [bstoilov/py3-pinterest#7]
Hey  I have a suggestion related to the path of where registry.dat should be saved currently its been saved in the folder of the lib in the pip packages folder which makes it harder to access 
it will be better generated on the same directory where the python file called the login function 
here on this line  https://github.com/bstoilov/py3-pinterest/blob/593f9d531f3c20d9889d65e3e23e74c571f61c0d/py3pin/Pinterest.py#L61

should be 
```self.data_path = os.path.join(cred_root,self.email) + os.sep```

**Comment by bstoilov** [comment]
This sounds like a good suggestion.

**Comment by elmissouri16** [comment]
> This sounds like a good suggestion.

great if you can add  it or I do pull request

**Comment by bstoilov** [comment]
I have merged your pull request.
