### ISSUE TITLE
Returning empty list of boards, pins

### ISSUE THREAD

**Issue by prithwis** [bstoilov/py3-pinterest#76]
the behaviour of the following commands is erratic :

- boards = pinterest.boards(username='xxxxxxx')
- pins = pinterest.board_feed(board_id=target_board['id'])

both commands are expected to return a list of either boards or pins and but sometimes they do ( as expected) and sometimes they return an empty list []

i am running these commands from a Google Colab notebook running in either a Chrome or Edge browser.
unable to replicate the problem all the time, but happens every now and then.

**Comment by aliayar** [comment]
Hello prithwis,

There is a comment for boards function.

>      The data returned is chunked, this comes from pinterest'a rest api.
        Some users might have huge number of boards that is why it make sense to chunk the data.
        In order to obtain all boards this method needs to be called until it returns empty list.

So, if returning empty list, it means that you have all the boards already. Testing this may help.

**Comment by bstoilov** [comment]
@aliayar is right. I realized this could be confusing so I included 'all' version for all of the batched methods.
To get all boards you can now use `boards_all` method.
Closing this, make sure your version of the client is up to date
