### ISSUE TITLE
How to get all pin by username

### ISSUE THREAD

**Issue by akayhanlar** [bstoilov/py3-pinterest#78]
I want to get all pins in a username. How can I do? Your program support only that, 'get all pins in boards'. But I want to all pin in with username.
Thanks..

**Comment by bstoilov** [comment]
Yes there is no single method you can use to get all user pins.
You need to first get all boards of the user:
`all_boards = pinterest.boards_all(username=username)`

and then for every board get the pins:
```
def get_board_pins_batched(board_id=''):
    board_feed = []
    feed_batch = pinterest.board_feed(board_id=board_id)
    while len(feed_batch) > 0:
        board_feed += feed_batch
        feed_batch = pinterest.board_feed(board_id=board_id)

    return board_feed

user_pins = []
for board in all_boards:
  user_pins += get_board_pins_batched(board['id])

# user_pins contains all pins of the user
```
