### ISSUE TITLE
Limit of search results

### ISSUE THREAD

**Issue by TRHX** [bstoilov/py3-pinterest#79]
Hi there. When I try to use the search method, no matter how large I change the value of max_items, the returned results will be about 900 to 1000 items. It is the same with changing other query parameters. How should I solve this problem?

```python
def search(max_items=9999, scope='boards', query='food'):
    results = []
    search_batch = pinterest.search(scope=scope, query=query)
    while len(search_batch) > 0 and len(results) < max_items:
        results += search_batch
        search_batch = pinterest.search(scope=scope, query=query)

    return results
```

In addition, I noticed that there are many duplicate data. Is there a bug?

**Comment by bstoilov** [comment]
This was reported a while ago by other users as well. It is a limitation from pinterest (1000 items max).

As for the duplicated data I am not able to reproduce it.
Here is the code I used to test:

```
res = search(max_items=1000, scope='boards', query='food')

print(len(res))
# prints 1000

ids = []
for r in res:
    if r['id'] not in ids:
        ids.append(r['id'])

print(print(len(ids)))
# prints 1000
```

Which means out of 1k results there are 1k unique ids. Perhaps I should try with different query?
