### ISSUE TITLE
Incorrect request url sometimes

### ISSUE THREAD

**Issue by imgVOID** [bstoilov/py3-pinterest#80]
Hello, I'm using py3-pinterest with Django, and sometimes it makes an incorrect Pinterest link with the same code. Getting boards always ok, only getting pins and getting sections causes a bug. I'm waiting some minutes and all becomes ok for a while. I don't change any line of code. 
Incorrect link (get//? not get/?):
https://www.pinterest.com/resource/BoardSectionPinsResource/get//?source_url=%2F&data=%7B%22options%22%3A%20%7B%22isPrefetch%22%3A%20false%2C%20%22field_set_key%22%3A%20%22react_grid_pin%22%2C%20%22is_own_profile_pins%22%3A%20true%2C%20%22page_size%22%3A%20250%2C%20%22redux_normalize_feed%22%3A%20true%2C%20%22section_id%22%3A%20%225116831258294404089%22%7D%2C%20%22context%22%3A%20null%7D&_=1601836906432
Can you explain me why this happens and how to fix it?

**Comment by imgVOID** [comment]
I've made this:
```
Pinterest.py get_board_sections():

url = self.req_builder.buildGet(url=GET_BOARD_SECTIONS, options=options)
url = url.replace('/get//?', '/get/?')
```

**Comment by bstoilov** [comment]
This is indeed strange behaviour. Will you make PR with your fix?

**Comment by bstoilov** [comment]
I included this directly in the `RequestBuilder` so it will be applied to all urls, in case something like this happens for other functionalities as well.
It is now included in the latest release.
