### ISSUE TITLE
How to pin to multi board ?

### ISSUE THREAD

**Issue by gijdoul** [bstoilov/py3-pinterest#84]
Hello is it possible to pin to multi board with your script ?

**Comment by bstoilov** [comment]
Are you referring to group boards? The API doesn't distinguish board by type. I am able to pin to any board as long as I have rights to do so, if no you will get `Forbidden` error

**Comment by gijdoul** [comment]
like this I mean I have the right to pin to those board but want to know if I can pin one to multi board at a time
pinterest.pin(board_id=(board_id1,board_id2,board_id3), image_url=image_url, description=description, title=title)

**Comment by bstoilov** [comment]
well no, but you can easily loop through the boards and pin on each one of them
