### ISSUE TITLE
pinterest.pin not working with instagram link

### ISSUE THREAD

**Issue by GenessyX** [bstoilov/py3-pinterest#85]
Hi, I am trying to repin image from instagram, but getting:
HTTPError: 403 Client Error: Forbidden for url: https://www.pinterest.com/resource/PinResource/create/

Works as expected for other urls.

`pin_response = pinterest.pin(board_id=target_board["id"],
                            image_url="https://www.instagram.com/p/CGNHiUonSDT/",
                            description="test",
                            title="test1")`

**Comment by imgVOID** [comment]
Maybe it's because you need to set directly link to the image, not to your Imstagram page's image showcase. I don't know try to test

**Comment by bstoilov** [comment]
Hi @GenessyX can you give us the code you are using?

**Comment by bstoilov** [comment]
Closing due to no reponse
