### ISSUE TITLE
script gives error on pinterest username

### ISSUE THREAD

**Issue by jjb99** [bstoilov/py3-pinterest#86]
Hello, I come to this place from [here](https://martechwithme.com/how-to-automate-pinterest-interactions-python/) and over there, there is some code for repinning,  that I don't see it here, maybe it has been taken out from here, 

I am a newbie, and don't know about python, just trying to make this script works,
I have installed python on my windows 7 64 bit, machine and installed library as well, I first tried the "download_board_images.py" on my Pinterest account and it worked fine and got images to my computer, 
so the script works,
anyhow, 
I am interested to try the code, that is proved to repin, pins from the selected board,  but I get an error when tried.
Here is  the code :

`
pinterest.login()

boards = pinterest.boards(username=username)

for board in boards:

    board_id = board['id']

    board_name = board['name']

    print("makeup" + board_name)
  
    search_batch = pinterest.search(scope='pins', query=board_name)
    
    time.sleep(random.randint(3,7))
    
    number_pin = random.randint(0,len(search_batch))
    
    pin_id = search_batch[number_pin]['id']
    
    name_pin = search_batch[number_pin]['domain']
    
    print("Repinning pin from " + name_pin)
    
    pinterest.repin(board_id=board_id,

                    pin_id=pin_id)
   
    time.sleep(random.randint(3,7))`

I have tried a couple of Pinterest accounts, to run this, here is one that I try to use:

https://www.pinterest.com/jennbatth12/

and here is where I put the username:
`boards = pinterest.boards(username=jennbatth12)`

but when I run it, I get an error: 
` line 16, in <module>
    boards = pinterest.boards(username=jennbatth12)
NameError: name 'jennbatth12' is not defined`

Does anyone know to resolve this issue? appreciate your help.

**Comment by bstoilov** [comment]
Hi, jennbatth12 without quotes is interpreted as a variable. You need to pass in 'jennbatth12'.
`NameError: name 'jennbatth12' is not defined` it is looking for a variable called jennbatth12

Other than that your code looks ok. Just keep in mind that search will probably return pins that you have already pinned, so perhaps you should track which pins you have already repined. Otherwise you will end up with duplicated repins.

Other option is to get all pin ids from the board you are pinning to and cross validate the pins already pinned, but this could be very slow if you have many pins in your boards

**Comment by jjb99** [comment]
thank you for your response, I added quotes and I don't get that error anymore,
 I have another issue now,
I want to repin other people's pins, not mine, and  I can not find board names, it seems that Pinterest has changed the board name viewing, now it is not viewable anymore, I am not sure if I can use this script,
 when you load an account you see, Created, Saved, and some account that made Shopping, you see Shopping, which in that case, on the right side there is a button that you can see the board name, but it does not show the board name on the address bar. so I am not sure how to get a board id when you don't' have the board name.

Thanks

**Comment by bstoilov** [comment]
Currently there is no way to get the board id by name. You can only get all boards of particular user. 
To repin other peopple's pins you can just use the repin function

**Comment by jjb99** [comment]
thanks for the reply, 
1- so how do I get all boards of a particular user?
2- having only board names, can I use the above script to repin? if so, I am not sure how to fill those places in the script, appreciate if anyone helps me out.

**Comment by bstoilov** [comment]
1.
To get all boards of a user
`pinterest.boards_all(username='username')`

2.
You can repin only to board you have access to so
`pinterest.boards_all()` without the user name will give all of your boards and then you can view their names and filter them

Also you can use the search with scope 'boards' it will give you list of boards matching the query
`scope: can be pins, buyable_pins, my_pins, videos, boards`

**Comment by jjb99** [comment]
Thanks for the reply, I could not make this works, 
 I tried a couple of variations to get something but with no result, I even have difficulty to find a board name of a user from Pinterest, how do you find the board names of a user?

anyhow I first tried this:
`pinterest = Pinterest(email='myemail',
                      password='my Pinterest pass',
                      username='my pin username',
                      cred_root='cred_root')
pinterest.login()
pinterest.boards_all(username='cancillageyerr')`

as you mentioned above.
to get board names of a user, I tried different random users, but nothing shows up, no error either, the script works for 2 to 4 sec, then nothing,

 I also tried the 
follow_examples.py
my login on top, and filled the query as well, I did not change anything.

`query = 'flower arrangements'
    scope = 'boards'
query = 'flower arrangements'
    scope = 'pins'`

I also tried the script for repinning that I put it on one of my post, the only place I filled was the top part which is my Pinterest login info, and this part:
`boards = pinterest.boards(username='cancillageyerr')`

I get no result, after a few seconds of running nothing happens, no error either.
what do I do wrong? 
I appreciate your help.

**Comment by bstoilov** [comment]
`pinterest.boards_all(username='cancillageyerr')` returns the pinterest json result as python object so you can't expect anything to show if you don't do something with it

Here is a small example to get you started:

```
boards_map = {}
for b in all_boards:
    boards_map[b['url']] = b['id']

for key in boards_map:
    print("board: " + key + " id: " + boards_map[key])
```

Output:
```
board: /cancillageyerr/f-a-l-l/ id: 833799387200885502
board: /cancillageyerr/n-a-i-l-s/ id: 833799387200885510
board: /cancillageyerr/halloween/ id: 833799387200903042
board: /cancillageyerr/bedroom/ id: 833799387200903756
board: /cancillageyerr/hair-ideas/ id: 833799387200904964
board: /cancillageyerr/makeuppp/ id: 833799387200910565
```

The follow is simpler you just need the user id. Same as for the board you get the pinterest response.

```
search_result_boards = search(max_items=10, scope='boards', query='food')

board_map = {}

for result in search_result_boards:
    board_map[result['id']] = result['url']

for key in board_map:
    print("board id: " + key + " board url: " + board_map[key])
```

Output:
```
board id: 16396054832349693 board url: /caitlin_cawley/food/
board id: 273171602336648264 board url: /plainchicken/food/
board id: 24488460412780871 board url: /iambaker/food/
board id: 124341708400887846 board url: /theforkedspoon/food-food-food/
board id: 269230952662756467 board url: /LifeAsMama/food/
board id: 130534157888543864 board url: /hercampus/food/
board id: 185773622068019520 board url: /thedesignfiles/food/
board id: 358106676559839900 board url: /society19/food/
board id: 304133849775548919 board url: /admagazinefr/food/
board id: 2885255950239656 board url: /alida_r/food/
board id: 231442937039290555 board url: /LuizaBo/food/
board id: 220395044203397375 board url: /bydawnnicole/food/
...
...
```

Then you can pick any board id you want from the map and follow it
`follow_board(board_id='16396054832349693')`

Just make sure to pass string to the board_id param not a number

**Comment by jjb99** [comment]
thanks for the reply; 
it was my bad, I thought all these scripts should work just by running after adding Pinterest login info and keywords, but it seems it is for people who know about python and JSON , which I don't know, 

anyhow thanks for the coding you provided, I tried it to see If I can get it to work,
I run both of your examples but I get errors, I think the variable 'search' and 'all_boards'  or 'boards_all' need to have some values, I tried to find value in other example python file, but I couldn't, here is what exactly I run with the errors I get:

`import random
import time
import os
from py3pin.Pinterest import Pinterest

pinterest = Pinterest(email='my pin email',
                      password='my pin password',
                      username='Tmy pin username',
                      cred_root='cred_root')

boards = pinterest.boards(username='cancillageyerr')
boards_map = {}
for b in all_boards:
    boards_map[b['url']] = b['id']
for key in boards_map:
    print("board: " + key + " id: " + boards_map[key])`

the error I got:
`line 16, in <module>
    for b in all_boards:
NameError: name 'all_boards' is not defined`

the other example I run:
`import random
import time
import os
from py3pin.Pinterest import Pinterest

pinterest = Pinterest(email='my pin email',
                      password='my pin password',
                      username='Tmy pin username',
                      cred_root='cred_root')

boards = pinterest.boards(username='cancillageyerr')

search_result_boards = search(max_items=10, scope='boards', query='food')

board_map = {}

for result in search_result_boards:
    board_map[result['id']] = result['url']

for key in board_map:
    print("board id: " + key + " board url: " + board_map[key])`

the error I get:
`
line 15, in <module>
    search_result_boards = search(max_items=10, scope='boards', query='food')
NameError: name 'search' is not defined`

thanks for your help.

**Comment by jjb99** [comment]
it seemed that 
`Pinterest.boards_all(username='cancillageyerr')`
with lower case p, give an error, I tried it with capital letter P,
I tried this:
`import random
import time
import os

from py3pin.Pinterest import Pinterest

username = 'xxx'
password = 'xxx'
email = 'xxx'
# cred_root is the place the user sessions and cookies will be stored you should specify this to avoid permission issues
cred_root = 'cred_root'

Pinterest.boards_all(username='cancillageyerr')
boards_map = {}
for b in all_boards:
    boards_map[b['url']] = b['id']

for key in boards_map:
    print("board: " + key + " id: " + boards_map[key])`

I get this error:
`line 14, in <module>
    Pinterest.boards_all(username='cancillageyerr')
TypeError: boards_all() missing 1 required positional argument: 'self'`

what I do wrongly, Thanks

**Comment by jjb99** [comment]
OK, after a long struggle with the above codes you posted with the result, I had some errors in my code, cleaned them up, 
downloaded the updated version, and replace the whole codes with an updated one, I tried both of them again, 
this time I get variable errors that is not defined, "search" and "all_boards" and other error that I write them below.
what do I do wrong?
 I appreciate your help,

I have searched and I did not find any variable called: "search" or "all_boards" in pinterest.py, 
I found a  class but it looks a little different, called "boards_all":
`def boards_all(self, username=None):`
even though I replaced the "all_boards" with "boards_all", I still get the same error

here are the exact codes I tried and the respective error:

`import random
import time
import os
import requests
from py3pin.Pinterest import Pinterest
pinterest = Pinterest(email='xxx',
                      password='xxx',
                      username='xxx',
                      cred_root='cred_root')
search_result_boards = search(max_items=10, scope='boards', query='weight loss')
board_map = {}
for result in search_result_boards:
    board_map[result['id']] = result['url']
for key in board_map:
    print("board id: " + key + " board url: " + board_map[key])`

I get this error:

`Pinterest.py:342: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if next_bookmark is '-end-':
Traceback (most recent call last):
  File "C:\Users\xxxx\Desktop\Python\py3-pinterest-master\z-get-board-id-names.py", line 13, in <module>
    search_result_boards = search(max_items=10, scope='boards', query='weight loss')
NameError: name 'search' is not defined`

and this is the other code I tried:

`import random
import time
import os
from py3pin.Pinterest import Pinterest
pinterest = Pinterest(email='xxx',
                      password='xxx',
                      username='xxx',
                      cred_root='cred_root')
pinterest.boards_all(username='cancillageyerr')
boards_map = {}
for b in all_boards:
    boards_map[b['url']] = b['id']
for key in boards_map:
    print("board: " + key + " id: " + boards_map[key])`

and I get this error:

`line 14, in <module>
    for b in all_boards:
NameError: name 'all_boards' is not defined`

Thank you again for your help, 
anyone who has tried these codes with results and know what I do wrongly please give me a tip or instruction, I know a little bit of python, and still learning. Thanks

**Comment by bstoilov** [comment]
Its is really hard for me to understand your code like that. In python tabs separate scopes. 
The second error is telling you that all_boards is no defined. You are not defining it anywhere.

`pinterest.boards_all(username='cancillageyerr') -> all_boards = pinterest.boards_all(username='cancillageyerr')
`

basically boards_all is a method (not a class) it returns some data, and you need to store the data into a variable in order to use it later.

The first error is telling you that it can't find 'search', That is because the way you are using it it expects a method called 'search' to be defined in the current scope.
You need to reference the search method of pinterest

`pinterest.search(..)
`

I have probably confused you because it ran my code inside examples.py, there is such method

**Comment by jjb99** [comment]
Thank you again for responding, I am grateful for your concern, I am improving my python and watching python tutorial as much I find the time, for now, I skip this search feature until I learn more about python,
the basic of python is not difficult to learn, but when it comes to making it work with Jason I am completely clueless. 

 But  I want to make the repin function that is in the example.py file works for me. 
I am not sure if this works on Repinning other people's pins as well or not, please let me know.
Because I don't want to repin my own pin, only other people's pin, I do find another method to search Pinterest and get pin numbers to be pinned on my board, that is what I want to do.
here is the code I found in example file:
`def repin(pin_id='', board_id='', section_id=None):
    return pinterest.repin(board_id=board_id, pin_id=pin_id, section_id=section_id)`

I have put the following in my repin file and tried it, but it returns nothing, nor any error:
`import json
import random
import time
import os
from py3pin.Pinterest import Pinterest
pinterest = Pinterest(email='my  acc email',
                      password='my  acc pass',
                      username='my acc username',
                      cred_root='cred_root')

def repin(pin_id='I put other's people pin no Here', board_id='I wput one of my board id number Here', section_id=None):
    return pinterest.repin(board_id=board_id, pin_id=pin_id, section_id=section_id)`

appreciate your help.

**Comment by jjb99** [comment]
OK, it works now, I have to add repin() at the end of my code.

**Comment by bstoilov** [comment]
Great! I will close the issue now, because it got way off topic. Feel free to open new one if you face other issue :)
