### ISSUE TITLE
i got this error today. yesterday it was working.TypeError: new() got an unexpected keyword argument 'email'

### ISSUE THREAD

**Issue by sjaydeep** [bstoilov/py3-pinterest#92]
If any one got this type of error, then check code it in normal python file and then link with module. because this is error from come from the any connectivity code which you had link. so check your code.

**Comment by bstoilov** [comment]
Can you give me a code sample? The client is working just fine on my machine

**Comment by sjaydeep** [comment]
This error showed me because of error of my code and it conflicts with our
py3 libraries. It is workikg fine now. Thank you for your time

**Comment by bstoilov** [comment]
Glad everything is working
