### ISSUE TITLE
How To Add Multiple Proxies

### ISSUE THREAD

**Issue by mazharoddin** [bstoilov/py3-pinterest#94]
Hi,
Can you please let me know how to add multiple proxies. 
I tried to add multiple proxies using comma-separated-values, but I am sure if that is the right way to add because I am not getting any error with the wrong proxy or non-working proxy.

Also, let me know if there is any way to find out if the proxy is working or not. 

Thanks.
-Mazhar

**Comment by bstoilov** [comment]
I am using the build in python mechanism, nothing too special.
https://blog.scrapinghub.com/python-requests-proxy

https://github.com/bstoilov/py3-pinterest/blob/master/py3pin/Pinterest.py#L102

so this will work
```
proxies = {
 “http”: “http://user:pass@10.10.10.10:8000”,
 “https”: “http://user:pass@10.10.10.10:8000”,
}
```

the requests package will rotate the proxies for you, so you don't need to worry about that.

I haven incorporated anything that will check if the proxies are working, but I test mine using 
http://checkip.amazonaws.com/
Simple get request with python will give you the IP and you can see if its different than yours and for every proxy.

**Comment by mazharoddin** [comment]
Ok, thanks for the reply...I will use aws ip checkup service to check the proxy status. Thanks.
