### ISSUE TITLE
getting error on commenting

### ISSUE THREAD

**Issue by jjb99** [bstoilov/py3-pinterest#96]
Hello, thank you for the code,  I have tried the comment part from the example file, and getting an error, 
I have tried few different pin numbers each time with it, but still getting the same error.
appreciate your help, 

Here is the code I tried:

`from py3pin.Pinterest import Pinterest 
pinterest = Pinterest(email='xxxx', 
                      password='xxx', 
                      username='xxx', 
                      cred_root='cred_root') 
def comment_on_pin(pin_id='616500636482444598', comment_text='it is nice!'): 
    return pinterest.comment(pin_id=pin_id, text=comment_text) 
comment_on_pin()`

and here is the error:
`Traceback (most recent call last):
  File "c:/Users/XXXX/Desktop/Python/py3-pinterest-master/z-comment-test.py", line 18, in <module>
    comment_on_pin() 
  File "c:/Users/XXXX/Desktop/Python/py3-pinterest-master/z-comment-test.py", line 17, in comment_on_pin
    return pinterest.comment(pin_id=pin_id, text=comment_text) 
  File "c:\Users\XXXX\Desktop\Python\py3-pinterest-master\py3pin\Pinterest.py", line 469, in comment
    pin_data = self.load_pin(pin_id=pin_id) 
  File "c:\Users\XXXX\Desktop\Python\py3-pinterest-master\py3pin\Pinterest.py", line 493, in load_pin
    return pin_data['pins'][str(pin_id)] 
KeyError: 'pins'`

**Comment by bstoilov** [comment]
It seems pinterest changed something in their API, working on this now.

**Comment by bstoilov** [comment]
https://github.com/bstoilov/py3-pinterest/pull/98

**Comment by DrunkCodes** [comment]
The comment is no longer working again

**Comment by bstoilov** [comment]
@DrunkCodes can you post your code?

**Comment by DrunkCodes** [comment]
The code am using is the same from the way it was explianed in the example.py file. Also this worked yesterday, but no more working .
Also to login is a problem it keep sending 401 and 429 error codes. 

Is it working in your own system?

**Comment by bstoilov** [comment]
Related to https://github.com/bstoilov/py3-pinterest/issues/108
